-- Generated from the Daggerheart SRD (srd.pdf) by scripts run on 2026-09-05.
-- Upserts keyed on slug: existing rows are updated in place (ids are preserved),
-- new rows are inserted. Rows whose slug no longer appears in the SRD are left
-- untouched and listed at the bottom of this file.
--
-- Run order: 01_domains, 02_subclasses, 03_classes, 04_ancestries, 05_communities,
--            06_abilities, 07_weapons, 08_armors, 09_items, 10_consumables

-- Includes the combat wheelchair models (Primary weapons; arcane frames use trait 'Spellcast').

insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  ('broadsword', 'Broadsword', 1, 'Primary', 'Agility', 'Melee', 'd8 phy', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('katana', 'Katana', 1, 'Primary', 'Agility', 'Melee', 'd10+3 phy', 'Two-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('longsword', 'Longsword', 1, 'Primary', 'Agility', 'Melee', 'd10+3 phy', 'Two-Handed', null, null),
  ('battleaxe', 'Battleaxe', 1, 'Primary', 'Strength', 'Melee', 'd10+3 phy', 'Two-Handed', null, null),
  ('brass-knuckles', 'Brass Knuckles', 1, 'Primary', 'Strength', 'Melee', 'd8+1 phy', 'One-Handed', null, null),
  ('greatsword', 'Greatsword', 1, 'Primary', 'Strength', 'Melee', 'd10+3 phy', 'Two-Handed', 'Massive', '−1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'),
  ('mace', 'Mace', 1, 'Primary', 'Strength', 'Melee', 'd8+1 phy', 'One-Handed', null, null),
  ('warhammer', 'Warhammer', 1, 'Primary', 'Strength', 'Melee', 'd12+3 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('dagger', 'Dagger', 1, 'Primary', 'Finesse', 'Melee', 'd8+1 phy', 'One-Handed', null, null),
  ('quarterstaff', 'Quarterstaff', 1, 'Primary', 'Instinct', 'Melee', 'd10+3 phy', 'Two-Handed', null, null),
  ('cutlass', 'Cutlass', 1, 'Primary', 'Presence', 'Melee', 'd8+1 phy', 'One-Handed', null, null),
  ('rapier', 'Rapier', 1, 'Primary', 'Presence', 'Melee', 'd8 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('scimitar', 'Scimitar', 1, 'Primary', 'Presence', 'Melee', 'd8+1 phy', 'One-Handed', null, null),
  ('twisted-dagger', 'Twisted Dagger', 1, 'Primary', 'Knowledge', 'Melee', 'd8 phy', 'One-Handed', 'Piercing', 'Damage dealt with this weapon treats the target’s Major threshold as having a −2 penalty.'),
  ('halberd', 'Halberd', 1, 'Primary', 'Strength', 'Very Close', 'd10+2 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('spear', 'Spear', 1, 'Primary', 'Finesse', 'Very Close', 'd8+3 phy', 'Two-Handed', null, null),
  ('whipsword', 'Whipsword', 1, 'Primary', 'Finesse', 'Very Close', 'd8 phy', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Finesse, Melee, d10.'),
  ('rope-dart', 'Rope Dart', 1, 'Primary', 'Instinct', 'Close', 'd6+1 phy', 'Two-Handed', null, null),
  ('shortbow', 'Shortbow', 1, 'Primary', 'Agility', 'Far', 'd6+3 phy', 'Two-Handed', null, null),
  ('crossbow', 'Crossbow', 1, 'Primary', 'Finesse', 'Far', 'd6+1 phy', 'One-Handed', null, null),
  ('longbow', 'Longbow', 1, 'Primary', 'Agility', 'Very Far', 'd8+3 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('arcane-gauntlets', 'Arcane Gauntlets', 1, 'Primary', 'Strength', 'Melee', 'd10+3 mag', 'Two-Handed', null, null),
  ('brightsword', 'Brightsword', 1, 'Primary', 'Strength', 'Melee', 'd10+3 mag', 'Two-Handed', null, null),
  ('hallowed-axe', 'Hallowed Axe', 1, 'Primary', 'Strength', 'Melee', 'd8+1 mag', 'One-Handed', null, null),
  ('shadowblade', 'Shadowblade', 1, 'Primary', 'Presence', 'Melee', 'd8 phy/mag', 'One-Handed', 'Otherworldly', 'On a successful attack, you can deal physical or magic damage.'),
  ('glowing-rings', 'Glowing Rings', 1, 'Primary', 'Agility', 'Very Close', 'd10+2 mag', 'Two-Handed', null, null),
  ('hand-runes', 'Hand Runes', 1, 'Primary', 'Instinct', 'Very Close', 'd10 mag', 'One-Handed', null, null),
  ('enchanted-chakram', 'Enchanted Chakram', 1, 'Primary', 'Finesse', 'Close', 'd6+1 mag', 'One-Handed', 'Ricochet', 'When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.'),
  ('returning-blade', 'Returning Blade', 1, 'Primary', 'Finesse', 'Close', 'd8 mag', 'One-Handed', 'Returning', 'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'),
  ('casting-dagger', 'Casting Dagger', 1, 'Primary', 'Instinct', 'Close', 'd6 mag', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Instinct, Melee, d8.'),
  ('shortstaff', 'Shortstaff', 1, 'Primary', 'Instinct', 'Close', 'd8+1 mag', 'One-Handed', null, null),
  ('dualstaff', 'Dualstaff', 1, 'Primary', 'Instinct', 'Far', 'd6+3 mag', 'Two-Handed', null, null),
  ('scepter', 'Scepter', 1, 'Primary', 'Presence', 'Far', 'd6 mag', 'Two-Handed', 'Versatile', 'This weapon can also be used with these statistics—Presence, Melee, d8.'),
  ('runelock-pistol', 'Runelock Pistol', 1, 'Primary', 'Knowledge', 'Far', 'd6+3 mag', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('wand', 'Wand', 1, 'Primary', 'Knowledge', 'Far', 'd6+1 mag', 'One-Handed', null, null),
  ('arcane-rifle', 'Arcane Rifle', 1, 'Primary', 'Agility', 'Very Far', 'd10+3 mag', 'Two-Handed', 'Aimed', 'Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.'),
  ('greatstaff', 'Greatstaff', 1, 'Primary', 'Knowledge', 'Very Far', 'd6 mag', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('improved-broadsword', 'Improved Broadsword', 2, 'Primary', 'Agility', 'Melee', 'd8+3 phy', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('improved-katana', 'Improved Katana', 2, 'Primary', 'Agility', 'Melee', 'd10+6 phy', 'Two-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('improved-longsword', 'Improved Longsword', 2, 'Primary', 'Agility', 'Melee', 'd10+6 phy', 'Two-Handed', null, null),
  ('improved-battleaxe', 'Improved Battleaxe', 2, 'Primary', 'Strength', 'Melee', 'd10+6 phy', 'Two-Handed', null, null),
  ('improved-brass-knuckles', 'Improved Brass Knuckles', 2, 'Primary', 'Strength', 'Melee', 'd8+4 phy', 'One-Handed', null, null),
  ('improved-greatsword', 'Improved Greatsword', 2, 'Primary', 'Strength', 'Melee', 'd10+6 phy', 'Two-Handed', 'Massive', '−1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'),
  ('improved-mace', 'Improved Mace', 2, 'Primary', 'Strength', 'Melee', 'd8+4 phy', 'One-Handed', null, null),
  ('improved-warhammer', 'Improved Warhammer', 2, 'Primary', 'Strength', 'Melee', 'd12+6 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('improved-dagger', 'Improved Dagger', 2, 'Primary', 'Finesse', 'Melee', 'd8+4 phy', 'One-Handed', null, null),
  ('improved-quarterstaff', 'Improved Quarterstaff', 2, 'Primary', 'Instinct', 'Melee', 'd10+6 phy', 'Two-Handed', null, null),
  ('improved-cutlass', 'Improved Cutlass', 2, 'Primary', 'Presence', 'Melee', 'd8+4 phy', 'One-Handed', null, null),
  ('improved-rapier', 'Improved Rapier', 2, 'Primary', 'Presence', 'Melee', 'd8+3 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('improved-scimitar', 'Improved Scimitar', 2, 'Primary', 'Presence', 'Melee', 'd8+4 phy', 'One-Handed', null, null),
  ('improved-twisted-dagger', 'Improved Twisted Dagger', 2, 'Primary', 'Knowledge', 'Melee', 'd8+3 phy', 'One-Handed', 'Piercing', 'Damage dealt with this weapon treats the target’s Major threshold as having a −2 penalty.'),
  ('improved-halberd', 'Improved Halberd', 2, 'Primary', 'Strength', 'Very Close', 'd10+5 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('improved-spear', 'Improved Spear', 2, 'Primary', 'Finesse', 'Very Close', 'd8+6 phy', 'Two-Handed', null, null),
  ('improved-whipsword', 'Improved Whipsword', 2, 'Primary', 'Finesse', 'Very Close', 'd8+3 phy', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Finesse, Melee, d10+3.'),
  ('improved-rope-dart', 'Improved Rope Dart', 2, 'Primary', 'Instinct', 'Close', 'd6+4 phy', 'Two-Handed', null, null),
  ('improved-shortbow', 'Improved Shortbow', 2, 'Primary', 'Agility', 'Far', 'd6+6 phy', 'Two-Handed', null, null),
  ('improved-crossbow', 'Improved Crossbow', 2, 'Primary', 'Finesse', 'Far', 'd6+4 phy', 'One-Handed', null, null),
  ('improved-longbow', 'Improved Longbow', 2, 'Primary', 'Agility', 'Very Far', 'd8+6 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('gilded-falchion', 'Gilded Falchion', 2, 'Primary', 'Strength', 'Melee', 'd10+4 phy', 'One-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('knuckle-blades', 'Knuckle Blades', 2, 'Primary', 'Strength', 'Melee', 'd10+6 phy', 'Two-Handed', 'Brutal', 'When you roll the maximum value on a damage die, roll an additional damage die.'),
  ('war-pick', 'War Pick', 2, 'Primary', 'Strength', 'Melee', 'd8+3 phy', 'One-Handed', 'Deadly', 'When you deal Severe damage, the target must mark an additional HP.'),
  ('cane-sword', 'Cane Sword', 2, 'Primary', 'Finesse', 'Melee', 'd8+4 phy', 'One-Handed', 'Retractable', 'The blade can be hidden in the cane to avoid detection.'),
  ('urok-broadsword', 'Urok Broadsword', 2, 'Primary', 'Finesse', 'Melee', 'd8+3 phy', 'One-Handed', 'Deadly', 'When you deal Severe damage, the target must mark an additional HP.'),
  ('bladed-fan', 'Bladed Fan', 2, 'Primary', 'Presence', 'Melee', 'd8+3 phy', 'One-Handed', 'Parry', 'When you are attacked, roll this weapon’s damage dice. If any of the attacker’s damage dice rolled the same value as your dice, the matching results are discarded from the attacker’s damage dice before the damage you take is totaled.'),
  ('cyrurgiens-scalpel', 'Cyrurgien’s Scalpel', 2, 'Primary', 'Knowledge', 'Melee', 'd8+3 phy', 'One-Handed', 'Scary', 'On a successful attack, the target must mark a Stress.'),
  ('bladed-whip', 'Bladed Whip', 2, 'Primary', 'Agility', 'Very Close', 'd8+3 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('javelins', 'Javelins', 2, 'Primary', 'Agility', 'Very Close', 'd6+6 phy', 'One-Handed', 'Stockpiled', 'You can throw this weapon at a target within Far range by making an attack roll using Agility without having to retrieve it, as you always have another one on hand.'),
  ('steelforged-halberd', 'Steelforged Halberd', 2, 'Primary', 'Strength', 'Very Close', 'd8+4 phy', 'Two-Handed', 'Scary', 'On a successful attack, the target must mark a Stress.'),
  ('war-scythe', 'War Scythe', 2, 'Primary', 'Finesse', 'Very Close', 'd8+5 phy', 'Two-Handed', 'Reliable', '+1 to attack rolls'),
  ('lance', 'Lance', 2, 'Primary', 'Instinct', 'Very Close', 'd10+5 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('blunderbuss', 'Blunderbuss', 2, 'Primary', 'Finesse', 'Close', 'd8+6 phy', 'Two-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('greatbow', 'Greatbow', 2, 'Primary', 'Strength', 'Far', 'd6+6 phy', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('finehair-bow', 'Finehair Bow', 2, 'Primary', 'Agility', 'Very Far', 'd6+5 phy', 'Two-Handed', 'Reliable', '+1 to attack rolls'),
  ('improved-arcane-gauntlets', 'Improved Arcane Gauntlets', 2, 'Primary', 'Strength', 'Melee', 'd10+6 mag', 'Two-Handed', null, null),
  ('improved-brightsword', 'Improved Brightsword', 2, 'Primary', 'Strength', 'Melee', 'd10+6 mag', 'Two-Handed', null, null),
  ('improved-hallowed-axe', 'Improved Hallowed Axe', 2, 'Primary', 'Strength', 'Melee', 'd8+4 mag', 'One-Handed', null, null),
  ('improved-shadowblade', 'Improved Shadowblade', 2, 'Primary', 'Presence', 'Melee', 'd8+3 phy/mag', 'One-Handed', 'Otherworldly', 'On a successful attack, you can deal physical or magic damage.'),
  ('improved-glowing-rings', 'Improved Glowing Rings', 2, 'Primary', 'Agility', 'Very Close', 'd10+5 mag', 'Two-Handed', null, null),
  ('improved-hand-runes', 'Improved Hand Runes', 2, 'Primary', 'Instinct', 'Very Close', 'd10+3 mag', 'One-Handed', null, null),
  ('improved-enchanted-chakram', 'Improved Enchanted Chakram', 2, 'Primary', 'Finesse', 'Close', 'd6+4 mag', 'One-Handed', 'Ricochet', 'When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.'),
  ('improved-returning-blade', 'Improved Returning Blade', 2, 'Primary', 'Finesse', 'Close', 'd8+3 mag', 'One-Handed', 'Returning', 'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'),
  ('improved-casting-dagger', 'Improved Casting Dagger', 2, 'Primary', 'Instinct', 'Close', 'd6+3 mag', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Instinct, Melee, d8+3.'),
  ('improved-shortstaff', 'Improved Shortstaff', 2, 'Primary', 'Instinct', 'Close', 'd8+4 mag', 'One-Handed', null, null),
  ('improved-dualstaff', 'Improved Dualstaff', 2, 'Primary', 'Instinct', 'Far', 'd6+6 mag', 'Two-Handed', null, null),
  ('improved-scepter', 'Improved Scepter', 2, 'Primary', 'Presence', 'Far', 'd6+3 mag', 'Two-Handed', 'Versatile', 'This weapon can also be used with these statistics—Presence, Melee, d8+3.'),
  ('improved-runelock-pistol', 'Improved Runelock Pistol', 2, 'Primary', 'Knowledge', 'Far', 'd6+6 mag', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('improved-wand', 'Improved Wand', 2, 'Primary', 'Knowledge', 'Far', 'd6+4 mag', 'One-Handed', null, null),
  ('improved-arcane-rifle', 'Improved Arcane Rifle', 2, 'Primary', 'Agility', 'Very Far', 'd10+6 mag', 'Two-Handed', 'Aimed', 'Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.'),
  ('improved-greatstaff', 'Improved Greatstaff', 2, 'Primary', 'Knowledge', 'Very Far', 'd6+3 mag', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('ego-blade', 'Ego Blade', 2, 'Primary', 'Agility', 'Melee', 'd12+4 mag', 'One-Handed', 'Pompous', 'You must have a Presence of 0 or lower to use this weapon.'),
  ('casting-sword', 'Casting Sword', 2, 'Primary', 'Strength', 'Melee', 'd10+4 mag', 'Two-Handed', 'Versatile', 'This weapon can also be used with these statistics—Knowledge, Far, d6+3.'),
  ('enchanted-shillelagh', 'Enchanted Shillelagh', 2, 'Primary', 'Strength', 'Melee', 'd8+3 mag', 'One-Handed', 'Protective', '+1 to your Armor Score'),
  ('devouring-dagger', 'Devouring Dagger', 2, 'Primary', 'Finesse', 'Melee', 'd8+4 mag', 'One-Handed', 'Scary', 'On a successful attack, the target must mark a Stress.'),
  ('displacement-razor', 'Displacement Razor', 2, 'Primary', 'Finesse', 'Melee', 'd8+3 mag', 'Two-Handed', 'Omnipresent', 'You can make attacks against targets within Very Far range, but must do so with disadvantage.'),
  ('hammer-of-exota', 'Hammer of Exota', 2, 'Primary', 'Instinct', 'Melee', 'd8+6 mag', 'Two-Handed', 'Eruptive', 'On a successful attack against a target within Melee range, all other adversaries within Very Close range must succeed on a reaction roll (14) or take half damage.'),
  ('spellbound-bangles', 'Spellbound Bangles', 2, 'Primary', 'Knowledge', 'Melee', 'd10+6 mag', 'Two-Handed', null, null),
  ('fury-gem', 'Fury Gem', 2, 'Primary', 'Instinct', 'Close', 'd8+3 mag', 'One-Handed', 'Burning', 'When you roll the maximum result on a damage die, the target must mark a Stress.'),
  ('enchanted-lute', 'Enchanted Lute', 2, 'Primary', 'Presence', 'Close', 'd8+3 mag', 'Two-Handed', 'Invigorating', 'On a successful attack, roll a d4. On a result of 4, clear a Stress.'),
  ('splintershaft-bow', 'Splintershaft Bow', 2, 'Primary', 'Agility', 'Far', 'd6+6 mag', 'Two-Handed', 'Volleyed', 'Spend a Hope to target a group of creatures within range. Targets you succeed against take half damage.'),
  ('yutari-bloodbow', 'Yutari Bloodbow', 2, 'Primary', 'Finesse', 'Far', 'd6+4 mag', 'Two-Handed', 'Brutal', 'When you roll the maximum value on a damage die, roll an additional damage die.'),
  ('elder-bow', 'Elder Bow', 2, 'Primary', 'Instinct', 'Far', 'd6+4 mag', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('scepter-of-elias', 'Scepter of Elias', 2, 'Primary', 'Presence', 'Far', 'd6+3 mag', 'One-Handed', 'Invigorating', 'On a successful attack, roll a d4. On a result of 4, clear a Stress.'),
  ('wand-of-enthrallment', 'Wand of Enthrallment', 2, 'Primary', 'Presence', 'Far', 'd6+4 mag', 'One-Handed', 'Persuasive', 'Before you make a Presence Roll, you can mark a Stress to gain a +2 bonus to the result.'),
  ('keepers-staff', 'Keeper''s Staff', 2, 'Primary', 'Knowledge', 'Far', 'd6+4 mag', 'Two-Handed', 'Reliable', '+1 to attack rolls'),
  ('advanced-broadsword', 'Advanced Broadsword', 3, 'Primary', 'Agility', 'Melee', 'd8+6 phy', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('advanced-katana', 'Advanced Katana', 3, 'Primary', 'Agility', 'Melee', 'd10+9 phy', 'Two-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('advanced-longsword', 'Advanced Longsword', 3, 'Primary', 'Agility', 'Melee', 'd10+9 phy', 'Two-Handed', null, null),
  ('advanced-battleaxe', 'Advanced Battleaxe', 3, 'Primary', 'Strength', 'Melee', 'd10+9 phy', 'Two-Handed', null, null),
  ('advanced-brass-knuckles', 'Advanced Brass Knuckles', 3, 'Primary', 'Strength', 'Melee', 'd8+7 phy', 'One-Handed', null, null),
  ('advanced-greatsword', 'Advanced Greatsword', 3, 'Primary', 'Strength', 'Melee', 'd10+9 phy', 'Two-Handed', 'Massive', '−1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'),
  ('advanced-mace', 'Advanced Mace', 3, 'Primary', 'Strength', 'Melee', 'd8+7 phy', 'One-Handed', null, null),
  ('advanced-warhammer', 'Advanced Warhammer', 3, 'Primary', 'Strength', 'Melee', 'd12+9 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('advanced-dagger', 'Advanced Dagger', 3, 'Primary', 'Finesse', 'Melee', 'd8+7 phy', 'One-Handed', null, null),
  ('advanced-quarterstaff', 'Advanced Quarterstaff', 3, 'Primary', 'Instinct', 'Melee', 'd10+9 phy', 'Two-Handed', null, null),
  ('advanced-cutlass', 'Advanced Cutlass', 3, 'Primary', 'Presence', 'Melee', 'd8+7 phy', 'One-Handed', null, null),
  ('advanced-rapier', 'Advanced Rapier', 3, 'Primary', 'Presence', 'Melee', 'd8+6 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('advanced-scimitar', 'Advanced Scimitar', 3, 'Primary', 'Presence', 'Melee', 'd8+7 phy', 'One-Handed', null, null),
  ('advanced-twisted-dagger', 'Advanced Twisted Dagger', 3, 'Primary', 'Knowledge', 'Melee', 'd8+6 phy', 'One-Handed', 'Piercing', 'Damage dealt with this weapon treats the target’s Major threshold as having a −2 penalty.'),
  ('advanced-halberd', 'Advanced Halberd', 3, 'Primary', 'Strength', 'Very Close', 'd10+8 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('advanced-spear', 'Advanced Spear', 3, 'Primary', 'Finesse', 'Very Close', 'd8+9 phy', 'Two-Handed', null, null),
  ('advanced-whipsword', 'Advanced Whipsword', 3, 'Primary', 'Finesse', 'Very Close', 'd8+6 phy', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Finesse, Melee, d10+6.'),
  ('advanced-rope-dart', 'Advanced Rope Dart', 3, 'Primary', 'Instinct', 'Close', 'd6+7 phy', 'Two-Handed', null, null),
  ('advanced-shortbow', 'Advanced Shortbow', 3, 'Primary', 'Agility', 'Far', 'd6+9 phy', 'Two-Handed', null, null),
  ('advanced-crossbow', 'Advanced Crossbow', 3, 'Primary', 'Finesse', 'Far', 'd6+7 phy', 'One-Handed', null, null),
  ('advanced-longbow', 'Advanced Longbow', 3, 'Primary', 'Agility', 'Very Far', 'd8+9 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('flickerfly-blade', 'Flickerfly Blade', 3, 'Primary', 'Agility', 'Melee', 'd8+5 phy', 'One-Handed', 'Sharpwing', 'Gain a bonus to your damage rolls equal to your Agility.'),
  ('blitz-hammer', 'Blitz Hammer', 3, 'Primary', 'Strength', 'Melee', 'd10+7 phy', 'Two-Handed', 'Accelerator', 'Once per scene, mark a Stress to move to Far range then make an attack. Gain a +1 bonus to your Proficiency on this attack.'),
  ('bravesword', 'Bravesword', 3, 'Primary', 'Strength', 'Melee', 'd12+7 phy', 'Two-Handed', 'Brave', '−1 to Evasion; +3 to Severe damage threshold'),
  ('hammer-of-wrath', 'Hammer of Wrath', 3, 'Primary', 'Strength', 'Melee', 'd10+7 phy', 'Two-Handed', 'Devastating', 'Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.'),
  ('labrys-axe', 'Labrys Axe', 3, 'Primary', 'Strength', 'Melee', 'd10+7 phy', 'Two-Handed', 'Protective', '+1 to Armor Score'),
  ('platinum-estoc', 'Platinum Estoc', 3, 'Primary', 'Finesse', 'Melee', 'd8+7 phy', 'One-Handed', 'Piercing', 'Damage dealt with this weapon treats the target’s Major threshold as having a −2 penalty.'),
  ('meridian-cutlass', 'Meridian Cutlass', 3, 'Primary', 'Presence', 'Melee', 'd10+5 phy', 'One-Handed', 'Dueling', 'When there are no other creatures within Close range of the target, gain advantage on your attack roll against them.'),
  ('retractable-saber', 'Retractable Saber', 3, 'Primary', 'Presence', 'Melee', 'd10+7 phy', 'One-Handed', 'Retractable', 'The blade can be hidden in the hilt to avoid detection.'),
  ('double-flail', 'Double Flail', 3, 'Primary', 'Agility', 'Very Close', 'd10+8 phy', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('soldiers-pike', 'Soldier’s Pike', 3, 'Primary', 'Agility', 'Very Close', 'd10+5 phy', 'Two-Handed', 'Braced', 'When an adversary within this weapon’s range deals damage to you, you can mark 2 Stress to force them to mark a Hit Point.'),
  ('chained-scythe', 'Chained Scythe', 3, 'Primary', 'Instinct', 'Very Close', 'd10+5 phy', 'Two-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('singing-sword', 'Singing Sword', 3, 'Primary', 'Presence', 'Very Close', 'd8+5 phy', 'One-Handed', 'Bolstering', 'When you critically succeed on an attack, all PCs within Close range gain a Hope.'),
  ('talon-blades', 'Talon Blades', 3, 'Primary', 'Finesse', 'Close', 'd10+7 phy', 'Two-Handed', 'Brutal', 'When you roll the maximum value on a damage die, roll an additional damage die.'),
  ('bladed-star', 'Bladed Star', 3, 'Primary', 'Knowledge', 'Close', 'd8+7 phy', 'One-Handed', 'Rebounding', 'When you throw this weapon, it returns to your hand. On a failed attack, you can reroll your attack with disadvantage.'),
  ('black-powder-revolver', 'Black Powder Revolver', 3, 'Primary', 'Finesse', 'Far', 'd6+8 phy', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('spiked-bow', 'Spiked Bow', 3, 'Primary', 'Agility', 'Very Far', 'd6+7 phy', 'Two-Handed', 'Versatile', 'This weapon can also be used with these statistics—Agility, Melee, d10+5.'),
  ('advanced-arcane-gauntlets', 'Advanced Arcane Gauntlets', 3, 'Primary', 'Strength', 'Melee', 'd10+9 mag', 'Two-Handed', null, null),
  ('advanced-brightsword', 'Advanced Brightsword', 3, 'Primary', 'Strength', 'Melee', 'd10+9 mag', 'Two-Handed', null, null),
  ('advanced-hallowed-axe', 'Advanced Hallowed Axe', 3, 'Primary', 'Strength', 'Melee', 'd8+7 mag', 'One-Handed', null, null),
  ('advanced-shadowblade', 'Advanced Shadowblade', 3, 'Primary', 'Presence', 'Melee', 'd8+6 phy/mag', 'One-Handed', 'Otherworldly', 'On a successful attack, you can deal physical or magic damage.'),
  ('advanced-glowing-rings', 'Advanced Glowing Rings', 3, 'Primary', 'Agility', 'Very Close', 'd10+8 mag', 'Two-Handed', null, null),
  ('advanced-hand-runes', 'Advanced Hand Runes', 3, 'Primary', 'Instinct', 'Very Close', 'd10+6 mag', 'One-Handed', null, null),
  ('advanced-enchanted-chakram', 'Advanced Enchanted Chakram', 3, 'Primary', 'Finesse', 'Close', 'd6+7 mag', 'One-Handed', 'Ricochet', 'When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.'),
  ('advanced-returning-blade', 'Advanced Returning Blade', 3, 'Primary', 'Finesse', 'Close', 'd8+6 mag', 'One-Handed', 'Returning', 'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'),
  ('advanced-casting-dagger', 'Advanced Casting Dagger', 3, 'Primary', 'Instinct', 'Close', 'd6+6 mag', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Instinct, Melee, d8+6.'),
  ('advanced-shortstaff', 'Advanced Shortstaff', 3, 'Primary', 'Instinct', 'Close', 'd8+7 mag', 'One-Handed', null, null),
  ('advanced-dualstaff', 'Advanced Dualstaff', 3, 'Primary', 'Instinct', 'Far', 'd6+9 mag', 'Two-Handed', null, null),
  ('advanced-scepter', 'Advanced Scepter', 3, 'Primary', 'Presence', 'Far', 'd6+6 mag', 'Two-Handed', 'Versatile', 'This weapon can also be used with these statistics—Presence, Melee, d8+4.'),
  ('advanced-runelock-pistol', 'Advanced Runelock Pistol', 3, 'Primary', 'Knowledge', 'Far', 'd6+9 mag', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('advanced-wand', 'Advanced Wand', 3, 'Primary', 'Knowledge', 'Far', 'd6+7 mag', 'One-Handed', null, null),
  ('advanced-arcane-rifle', 'Advanced Arcane Rifle', 3, 'Primary', 'Agility', 'Very Far', 'd10+9 mag', 'Two-Handed', 'Aimed', 'Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.'),
  ('advanced-greatstaff', 'Advanced Greatstaff', 3, 'Primary', 'Knowledge', 'Very Far', 'd6+6 mag', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('rocket-maul', 'Rocket Maul', 3, 'Primary', 'Strength', 'Melee', 'd10+7 mag', 'Two-Handed', 'Concussive', 'On a successful attack, you can spend a Hope to knock the target back to Far range.'),
  ('crystal-spear', 'Crystal Spear', 3, 'Primary', 'Finesse', 'Very Close', 'd10+6 mag', 'One-Handed', 'Piercing', 'Damage dealt with this weapon treats the target’s Major threshold as having a −2 penalty.'),
  ('arc-wand', 'Arc Wand', 3, 'Primary', 'Presence', 'Close', 'd8+6 mag', 'One-Handed', 'Bouncing', 'Mark any number of Stress to target that many additional creatures in range of the attack.'),
  ('rime-scepter', 'Rime Scepter', 3, 'Primary', 'Knowledge', 'Close', 'd8+6 mag', 'One-Handed', 'Freezing', 'When an attack from this weapon causes a target to mark 2 or more HP, they become temporarily Restrained.'),
  ('gunblade', 'Gunblade', 3, 'Primary', 'Agility', 'Far', 'd6+6 mag', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Agility, Melee, d8+6 phy.'),
  ('staff-of-augma', 'Staff of Augma', 3, 'Primary', 'Instinct', 'Far', 'd6+7 mag', 'One-Handed', 'Catalytic', 'On a successful attack, you can mark a Stress to give an ally within Close range a +3 bonus to their next attack roll.'),
  ('legendary-broadsword', 'Legendary Broadsword', 4, 'Primary', 'Agility', 'Melee', 'd8+9 phy', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('legendary-katana', 'Legendary Katana', 4, 'Primary', 'Agility', 'Melee', 'd10+12 phy', 'Two-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('legendary-longsword', 'Legendary Longsword', 4, 'Primary', 'Agility', 'Melee', 'd10+12 phy', 'Two-Handed', null, null),
  ('legendary-battleaxe', 'Legendary Battleaxe', 4, 'Primary', 'Strength', 'Melee', 'd10+12 phy', 'Two-Handed', null, null),
  ('legendary-brass-knuckles', 'Legendary Brass Knuckles', 4, 'Primary', 'Strength', 'Melee', 'd8+10 phy', 'One-Handed', null, null),
  ('legendary-greatsword', 'Legendary Greatsword', 4, 'Primary', 'Strength', 'Melee', 'd10+12 phy', 'Two-Handed', 'Massive', '−1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'),
  ('legendary-mace', 'Legendary Mace', 4, 'Primary', 'Strength', 'Melee', 'd8+10 phy', 'One-Handed', null, null),
  ('legendary-warhammer', 'Legendary Warhammer', 4, 'Primary', 'Strength', 'Melee', 'd12+12 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('legendary-dagger', 'Legendary Dagger', 4, 'Primary', 'Finesse', 'Melee', 'd8+10 phy', 'One-Handed', null, null),
  ('legendary-quarterstaff', 'Legendary Quarterstaff', 4, 'Primary', 'Instinct', 'Melee', 'd10+12 phy', 'Two-Handed', null, null),
  ('legendary-cutlass', 'Legendary Cutlass', 4, 'Primary', 'Presence', 'Melee', 'd8+10 phy', 'One-Handed', null, null),
  ('legendary-rapier', 'Legendary Rapier', 4, 'Primary', 'Presence', 'Melee', 'd8+9 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('legendary-scimitar', 'Legendary Scimitar', 4, 'Primary', 'Presence', 'Melee', 'd8+10 phy', 'One-Handed', null, null),
  ('legendary-twisted-dagger', 'Legendary Twisted Dagger', 4, 'Primary', 'Knowledge', 'Melee', 'd8+9 phy', 'One-Handed', 'Piercing', 'Damage dealt with this weapon treats the target’s Major threshold as having a −2 penalty.'),
  ('legendary-halberd', 'Legendary Halberd', 4, 'Primary', 'Strength', 'Very Close', 'd10+11 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('legendary-spear', 'Legendary Spear', 4, 'Primary', 'Finesse', 'Very Close', 'd8+12 phy', 'Two-Handed', null, null),
  ('legendary-whipsword', 'Legendary Whipsword', 4, 'Primary', 'Finesse', 'Very Close', 'd8+9 phy', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Finesse, Melee, d10+9.'),
  ('legendary-rope-dart', 'Legendary Rope Dart', 4, 'Primary', 'Instinct', 'Close', 'd6+10 phy', 'Two-Handed', null, null),
  ('legendary-shortbow', 'Legendary Shortbow', 4, 'Primary', 'Agility', 'Far', 'd6+12 phy', 'Two-Handed', null, null),
  ('legendary-crossbow', 'Legendary Crossbow', 4, 'Primary', 'Finesse', 'Far', 'd6+10 phy', 'One-Handed', null, null),
  ('legendary-longbow', 'Legendary Longbow', 4, 'Primary', 'Agility', 'Very Far', 'd8+12 phy', 'Two-Handed', 'Cumbersome', '−1 to Finesse'),
  ('dual-ended-sword', 'Dual-Ended Sword', 4, 'Primary', 'Agility', 'Melee', 'd10+9 phy', 'Two-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('impact-gauntlet', 'Impact Gauntlet', 4, 'Primary', 'Strength', 'Melee', 'd10+11 phy', 'One-Handed', 'Concussive', 'On a successful attack, you can spend a Hope to knock the target back to Far range.'),
  ('sledge-axe', 'Sledge Axe', 4, 'Primary', 'Strength', 'Melee', 'd12+13 phy', 'Two-Handed', 'Destructive', '−1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.'),
  ('curved-dagger', 'Curved Dagger', 4, 'Primary', 'Finesse', 'Melee', 'd8+9 phy', 'One-Handed', 'Serrated', 'When you roll a 1 on a damage die, it deals 8 damage instead.'),
  ('severed-dragon-claw', 'Severed Dragon Claw', 4, 'Primary', 'Instinct', 'Melee', 'd10+11 phy', 'One-Handed', 'Destructive', '−1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.'),
  ('infinite-staff', 'Infinite Staff', 4, 'Primary', 'Presence', 'Melee', 'd10+9 phy', 'Two-Handed', 'Extending', 'You can increase the range of this weapon up to Very Far. You gain a −1 penalty to attack rolls for each step you increase the range by (such as Melee to Very Close, Very Close to Close, or Close to Far).'),
  ('bec-de-corbin', 'Bec de Corbin', 4, 'Primary', 'Agility', 'Very Close', 'd10+9 phy', 'Two-Handed', 'Devastating', 'Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.'),
  ('extended-polearm', 'Extended Polearm', 4, 'Primary', 'Finesse', 'Very Close', 'd8+10 phy', 'Two-Handed', 'Long', 'This weapon’s attack targets all adversaries in a line within range.'),
  ('swinging-ropeblade', 'Swinging Ropeblade', 4, 'Primary', 'Presence', 'Close', 'd8+9 phy', 'Two-Handed', 'Grappling', 'On a successful attack, you can spend a Hope to Restrain the target or pull them into Melee range with you.'),
  ('black-powder-serpentine', 'Black Powder Serpentine', 4, 'Primary', 'Strength', 'Far', 'd8+12 phy', 'Two-Handed', 'Incendiary', '−1 to Agility; on a successful attack, all creatures within Very Close range of the target must mark a Hit Point.'),
  ('ricochet-axes', 'Ricochet Axes', 4, 'Primary', 'Agility', 'Far', 'd6+11 phy', 'Two-Handed', 'Bouncing', 'Mark 1 or more Stress to hit that many targets in range of the attack.'),
  ('aantari-bow', 'Aantari Bow', 4, 'Primary', 'Finesse', 'Far', 'd6+11 phy', 'Two-Handed', 'Reliable', '+1 to attack rolls'),
  ('clockwork-crossbow', 'Clockwork Crossbow', 4, 'Primary', 'Finesse', 'Far', 'd6+11 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('arquebus', 'Arquebus', 4, 'Primary', 'Knowledge', 'Far', 'd8+10 phy', 'Two-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('hand-cannon', 'Hand Cannon', 4, 'Primary', 'Finesse', 'Very Far', 'd6+12 phy', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('legendary-arcane-gauntlets', 'Legendary Arcane Gauntlets', 4, 'Primary', 'Strength', 'Melee', 'd10+12 mag', 'Two-Handed', null, null),
  ('legendary-brightsword', 'Legendary Brightsword', 4, 'Primary', 'Strength', 'Melee', 'd10+12 mag', 'Two-Handed', null, null),
  ('legendary-hallowed-axe', 'Legendary Hallowed Axe', 4, 'Primary', 'Strength', 'Melee', 'd8+10 mag', 'One-Handed', null, null),
  ('legendary-shadowblade', 'Legendary Shadowblade', 4, 'Primary', 'Presence', 'Melee', 'd8+9 phy/mag', 'One-Handed', 'Otherworldly', 'On a successful attack, you can deal physical or magic damage.'),
  ('legendary-glowing-rings', 'Legendary Glowing Rings', 4, 'Primary', 'Agility', 'Very Close', 'd10+11 mag', 'Two-Handed', null, null),
  ('legendary-hand-runes', 'Legendary Hand Runes', 4, 'Primary', 'Instinct', 'Very Close', 'd10+9 mag', 'One-Handed', null, null),
  ('legendary-enchanted-chakram', 'Legendary Enchanted Chakram', 4, 'Primary', 'Finesse', 'Close', 'd6+10 mag', 'One-Handed', 'Ricochet', 'When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.'),
  ('legendary-returning-blade', 'Legendary Returning Blade', 4, 'Primary', 'Finesse', 'Close', 'd8+9 mag', 'One-Handed', 'Returning', 'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'),
  ('legendary-casting-dagger', 'Legendary Casting Dagger', 4, 'Primary', 'Instinct', 'Close', 'd6+9 mag', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Instinct, Melee, d8+9.'),
  ('legendary-shortstaff', 'Legendary Shortstaff', 4, 'Primary', 'Instinct', 'Close', 'd8+10 mag', 'One-Handed', null, null),
  ('legendary-dualstaff', 'Legendary Dualstaff', 4, 'Primary', 'Instinct', 'Far', 'd8+12 mag', 'Two-Handed', null, null),
  ('legendary-scepter', 'Legendary Scepter', 4, 'Primary', 'Presence', 'Far', 'd6+9 mag', 'Two-Handed', 'Versatile', 'This weapon can also be used with these statistics—Presence, Melee, d8+6.'),
  ('legendary-runelock-pistol', 'Legendary Runelock Pistol', 4, 'Primary', 'Knowledge', 'Far', 'd6+12 mag', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('legendary-wand', 'Legendary Wand', 4, 'Primary', 'Knowledge', 'Far', 'd6+10 mag', 'One-Handed', null, null),
  ('legendary-arcane-rifle', 'Legendary Arcane Rifle', 4, 'Primary', 'Agility', 'Very Far', 'd10+12 mag', 'Two-Handed', 'Aimed', 'Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.'),
  ('legendary-greatstaff', 'Legendary Greatstaff', 4, 'Primary', 'Knowledge', 'Very Far', 'd6+9 mag', 'Two-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('starmetal-blade', 'Starmetal Blade', 4, 'Primary', 'Agility', 'Melee', 'd8+10 mag', 'One-Handed', 'Serrated', 'When you roll a 1 on a damage die, it deals 8 damage instead.'),
  ('sword-of-light-and-flame', 'Sword of Light & Flame', 4, 'Primary', 'Strength', 'Melee', 'd10+11 mag', 'Two-Handed', 'Hot', 'This weapon cuts through solid material.'),
  ('adders-fang', 'Adder’s Fang', 4, 'Primary', 'Finesse', 'Melee', 'd8+9 mag', 'One-Handed', 'Venomous', 'When you deal Major or greater damage with this weapon, the target becomes temporarily Vulnerable.'),
  ('demons-edge', 'Demon’s Edge', 4, 'Primary', 'Presence', 'Melee', 'd8+10 mag', 'One-Handed', 'Disturbing', 'When you defeat a creature with this weapon, all adversaries within Close range must mark a Stress.'),
  ('siphoning-gauntlets', 'Siphoning Gauntlets', 4, 'Primary', 'Presence', 'Melee', 'd10+9 mag', 'Two-Handed', 'Lifestealing', 'On a successful attack, roll a d6. On a result of 6, clear a Hit Point or clear a Stress.'),
  ('midas-scythe', 'Midas Scythe', 4, 'Primary', 'Knowledge', 'Melee', 'd10+9 mag', 'Two-Handed', 'Greedy', 'Spend a handful of gold to gain a +1 bonus to your Proficiency on a damage roll.'),
  ('storm-gods-greataxe', 'Storm God’s Greataxe', 4, 'Primary', 'Strength', 'Very Close', 'd10+9 mag', 'Two-Handed', 'Bouncing', 'Mark any number of Stress to target that many additional creatures in range of the attack.'),
  ('ethereal-zweihander', 'Ethereal Zweihänder', 4, 'Primary', 'Instinct', 'Very Close', 'd10+9 mag', 'Two-Handed', 'Ethereal', 'You must mark a Stress to conjure this weapon. It lasts until the end of the scene.'),
  ('floating-bladeshards', 'Floating Bladeshards', 4, 'Primary', 'Instinct', 'Close', 'd8+9 mag', 'One-Handed', 'Powerful', 'On a successful attack, roll an additional damage die and discard the lowest result.'),
  ('bloodstaff', 'Bloodstaff', 4, 'Primary', 'Instinct', 'Far', 'd20+7 mag', 'Two-Handed', 'Painful', 'Each time you make a successful attack, you must mark a Stress.'),
  ('thistlebow', 'Thistlebow', 4, 'Primary', 'Instinct', 'Far', 'd6+13 mag', 'Two-Handed', 'Reliable', '+1 to attack rolls'),
  ('gravity-arbalest', 'Gravity Arbalest', 4, 'Primary', 'Knowledge', 'Far', 'd8+6 mag', 'Two-Handed', 'Magnetic', 'When you make an attack with this weapon, you can spend a Hope to force all adversaries within Very Close range of the target to make a Reaction Roll (16). Creatures who fail must mark a Stress and are pulled into Melee range of the target.'),
  ('wand-of-essek', 'Wand of Essek', 4, 'Primary', 'Knowledge', 'Far', 'd8+13 mag', 'One-Handed', 'Timebending', 'You can choose the target of your attack after making your attack roll.'),
  ('magus-revolver', 'Magus Revolver', 4, 'Primary', 'Finesse', 'Very Far', 'd6+13 mag', 'One-Handed', 'Reloading', 'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'),
  ('fusion-gloves', 'Fusion Gloves', 4, 'Primary', 'Knowledge', 'Very Far', 'd6+9 mag', 'Two-Handed', 'Bonded', 'Gain a bonus to your damage rolls equal to your level.'),
  ('hatchet', 'Hatchet', 1, 'Secondary', 'Agility', 'Melee', 'd8 phy', 'One-Handed', 'Follow-Up', 'On a successful attack with your primary weapon within Melee range, you can mark a Stress to gain a +1 bonus to your Proficiency for this attack.'),
  ('shortsword', 'Shortsword', 1, 'Secondary', 'Agility', 'Melee', 'd8 phy', 'One-Handed', 'Paired', '+2 to primary weapon damage to targets within Melee range'),
  ('offhand-brass-knuckles', 'Offhand Brass Knuckles', 1, 'Secondary', 'Strength', 'Melee', 'd8 phy', 'One-Handed', 'Paired', '+2 to primary weapon damage to targets within Melee range'),
  ('round-shield', 'Round Shield', 1, 'Secondary', 'Strength', 'Melee', 'd4 phy', 'One-Handed', 'Protective', '+1 to Armor Score'),
  ('tower-shield', 'Tower Shield', 1, 'Secondary', 'Strength', 'Melee', 'd6 phy', 'One-Handed', 'Barrier', '+2 to Armor Score; −1 to Evasion'),
  ('small-dagger', 'Small Dagger', 1, 'Secondary', 'Finesse', 'Melee', 'd8 phy', 'One-Handed', 'Paired', '+2 to primary weapon damage to targets within Melee range'),
  ('throwing-knives', 'Throwing Knives', 1, 'Secondary', 'Finesse', 'Melee', 'd8 phy', 'One-Handed', 'Stockpiled', 'You can throw this weapon within Close range by making an attack roll using Finesse. You don’t have to retrieve it, as you always have another on hand.'),
  ('fighting-cloak', 'Fighting Cloak', 1, 'Secondary', 'Presence', 'Melee', 'd4 phy', 'One-Handed', 'Padded', '+2 to damage thresholds'),
  ('rune-shield', 'Rune Shield', 1, 'Secondary', 'Knowledge', 'Melee', 'd4 mag', 'One-Handed', 'Protective', '+1 to Armor Score'),
  ('focus-runes', 'Focus Runes', 1, 'Secondary', 'Instinct', 'Very Close', 'd6 mag', 'One-Handed', 'Focused', '+1 to primary weapon damage to targets within Very Close range'),
  ('whip', 'Whip', 1, 'Secondary', 'Presence', 'Very Close', 'd6 phy', 'One-Handed', 'Startling', 'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'),
  ('grappler', 'Grappler', 1, 'Secondary', 'Finesse', 'Close', 'd6 phy', 'One-Handed', 'Hooked', 'On a successful attack, you can pull the target into Melee range.'),
  ('hand-crossbow', 'Hand Crossbow', 1, 'Secondary', 'Finesse', 'Far', 'd6+1 phy', 'One-Handed', null, null),
  ('improved-hatchet', 'Improved Hatchet', 2, 'Secondary', 'Agility', 'Melee', 'd8+2 phy', 'One-Handed', 'Follow-Up', 'On a successful attack with your primary weapon within Melee range, you can mark a Stress to gain a +1 bonus to your Proficiency for this attack.'),
  ('improved-shortsword', 'Improved Shortsword', 2, 'Secondary', 'Agility', 'Melee', 'd8+2 phy', 'One-Handed', 'Paired', '+3 to primary weapon damage to targets within Melee range'),
  ('improved-offhand-brass-knuckles', 'Improved Offhand Brass Knuckles', 2, 'Secondary', 'Strength', 'Melee', 'd8+2 phy', 'One-Handed', 'Paired', '+3 to primary weapon damage to targets within Melee range'),
  ('improved-round-shield', 'Improved Round Shield', 2, 'Secondary', 'Strength', 'Melee', 'd4+2 phy', 'One-Handed', 'Protective', '+2 to Armor Score'),
  ('improved-tower-shield', 'Improved Tower Shield', 2, 'Secondary', 'Strength', 'Melee', 'd6+2 phy', 'One-Handed', 'Barrier', '+3 to Armor Score; −1 to Evasion'),
  ('improved-small-dagger', 'Improved Small Dagger', 2, 'Secondary', 'Finesse', 'Melee', 'd8+2 phy', 'One-Handed', 'Paired', '+3 to primary weapon damage to targets within Melee range'),
  ('improved-throwing-knives', 'Improved Throwing Knives', 2, 'Secondary', 'Finesse', 'Melee', 'd8+2 phy', 'One-Handed', 'Stockpiled', 'You can throw this weapon within Close range by making an attack roll using Finesse. You don’t have to retrieve it, as you always have another on hand.'),
  ('improved-fighting-cloak', 'Improved Fighting Cloak', 2, 'Secondary', 'Presence', 'Melee', 'd4+2 phy', 'One-Handed', 'Padded', '+3 to damage thresholds'),
  ('improved-rune-shield', 'Improved Rune Shield', 2, 'Secondary', 'Knowledge', 'Melee', 'd4+2 mag', 'One-Handed', 'Protective', '+2 to Armor Score'),
  ('improved-focus-runes', 'Improved Focus Runes', 2, 'Secondary', 'Instinct', 'Very Close', 'd6+2 mag', 'One-Handed', 'Focused', '+1 to primary weapon damage to targets within Very Close range'),
  ('improved-whip', 'Improved Whip', 2, 'Secondary', 'Presence', 'Very Close', 'd6+2 phy', 'One-Handed', 'Startling', 'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'),
  ('improved-grappler', 'Improved Grappler', 2, 'Secondary', 'Finesse', 'Close', 'd6+2 phy', 'One-Handed', 'Hooked', 'On a successful attack, you can pull the target into Melee range.'),
  ('improved-hand-crossbow', 'Improved Hand Crossbow', 2, 'Secondary', 'Finesse', 'Far', 'd6+3 phy', 'One-Handed', null, null),
  ('collapsible-baton', 'Collapsible Baton', 2, 'Secondary', 'Strength', 'Melee', 'd8 phy', 'One-Handed', 'Nonlethal', 'When a target would mark any number of Hit Points from an attack with this weapon, they mark an equal number of Stress instead.'),
  ('spiked-shield', 'Spiked Shield', 2, 'Secondary', 'Strength', 'Melee', 'd6+2 phy', 'One-Handed', 'Double Duty', '+1 to Armor Score; +1 to primary weapon damage within Melee range'),
  ('parrying-dagger', 'Parrying Dagger', 2, 'Secondary', 'Finesse', 'Melee', 'd6+2 phy', 'One-Handed', 'Parry', 'When you are attacked, roll this weapon''s damage dice. If any of the attacker''s damage dice rolled the same value as your dice, the matching results are discarded from the attacker''s damage dice before the damage you take is totaled.'),
  ('eldritch-vambrace', 'Eldritch Vambrace', 2, 'Secondary', 'Instinct', 'Melee', 'd8 mag', 'One-Handed', 'Deflecting', 'When you are attacked, you can mark an Armor Slot to gain a bonus to your Evasion equal to your Armor Score against the attack.'),
  ('segmented-staff', 'Segmented Staff', 2, 'Secondary', 'Agility', 'Very Close', 'd6+4 phy', 'One-Handed', 'Double Duty', '+1 to Armor Score; +1 to primary weapon damage within Melee range'),
  ('razor-wire', 'Razor Wire', 2, 'Secondary', 'Finesse', 'Very Close', 'd6+3 phy', 'One-Handed', 'Entangling', 'On a successful attack with your primary weapon against a target within Very Close range, you can spend a Hope to make the target temporarily Vulnerable.'),
  ('returning-axe', 'Returning Axe', 2, 'Secondary', 'Agility', 'Close', 'd6+4 phy', 'One-Handed', 'Returning', 'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'),
  ('advanced-hatchet', 'Advanced Hatchet', 3, 'Secondary', 'Agility', 'Melee', 'd8+4 phy', 'One-Handed', 'Follow-Up', 'On a successful attack with your primary weapon within Melee range, you can mark a Stress to gain a +1 bonus to your Proficiency for this attack.'),
  ('advanced-shortsword', 'Advanced Shortsword', 3, 'Secondary', 'Agility', 'Melee', 'd8+4 phy', 'One-Handed', 'Paired', '+4 to primary weapon damage to targets within Melee range'),
  ('advanced-offhand-brass-knuckles', 'Advanced Offhand Brass Knuckles', 3, 'Secondary', 'Strength', 'Melee', 'd8+4 phy', 'One-Handed', 'Paired', '+4 to primary weapon damage to targets within Melee range'),
  ('advanced-round-shield', 'Advanced Round Shield', 3, 'Secondary', 'Strength', 'Melee', 'd4+4 phy', 'One-Handed', 'Protective', '+3 to Armor Score'),
  ('advanced-tower-shield', 'Advanced Tower Shield', 3, 'Secondary', 'Strength', 'Melee', 'd6+4 phy', 'One-Handed', 'Barrier', '+4 to Armor Score; −1 to Evasion'),
  ('advanced-small-dagger', 'Advanced Small Dagger', 3, 'Secondary', 'Finesse', 'Melee', 'd8+4 phy', 'One-Handed', 'Paired', '+4 to primary weapon damage to targets within Melee range'),
  ('advanced-throwing-knives', 'Advanced Throwing Knives', 3, 'Secondary', 'Finesse', 'Melee', 'd8+4 phy', 'One-Handed', 'Stockpiled', 'You can throw this weapon within Close range by making an attack roll using Finesse. You don’t have to retrieve it, as you always have another on hand.'),
  ('advanced-fighting-cloak', 'Advanced Fighting Cloak', 3, 'Secondary', 'Presence', 'Melee', 'd4+4 phy', 'One-Handed', 'Padded', '+4 to damage thresholds'),
  ('advanced-rune-shield', 'Advanced Rune Shield', 3, 'Secondary', 'Knowledge', 'Melee', 'd4+4 mag', 'One-Handed', 'Protective', '+3 to Armor Score'),
  ('advanced-focus-runes', 'Advanced Focus Runes', 3, 'Secondary', 'Instinct', 'Very Close', 'd6+4 mag', 'One-Handed', 'Focused', '+1 to primary weapon damage to targets within Very Close range'),
  ('advanced-whip', 'Advanced Whip', 3, 'Secondary', 'Presence', 'Very Close', 'd6+4 phy', 'One-Handed', 'Startling', 'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'),
  ('advanced-grappler', 'Advanced Grappler', 3, 'Secondary', 'Finesse', 'Close', 'd6+4 phy', 'One-Handed', 'Hooked', 'On a successful attack, you can pull the target into Melee range.'),
  ('advanced-hand-crossbow', 'Advanced Hand Crossbow', 3, 'Secondary', 'Finesse', 'Far', 'd6+5 phy', 'One-Handed', null, null),
  ('buckler', 'Buckler', 3, 'Secondary', 'Agility', 'Melee', 'd4+4 phy', 'One-Handed', 'Deflecting', 'When you are attacked, you can mark an Armor Slot to gain a bonus to your Evasion equal to your available Armor Score against the attack.'),
  ('tinkers-hammer', 'Tinker’s Hammer', 3, 'Secondary', 'Strength', 'Melee', 'd8+4 phy', 'One-Handed', 'Trusty', '+1 to attack rolls made with your primary weapon'),
  ('vorpal-shard', 'Vorpal Shard', 3, 'Secondary', 'Knowledge', 'Melee', 'd4 mag', 'One-Handed', 'Targeted', 'When you fail a weapon attack, you can spend a Hope to succeed on your next weapon attack.'),
  ('soul-chain', 'Soul Chain', 3, 'Secondary', 'Presence', 'Very Close', 'd6+5 mag', 'One-Handed', 'Draining', 'On a successful attack, you can spend a Hope to force the target to mark a Stress. If they do, you clear a Stress.'),
  ('powered-gauntlet', 'Powered Gauntlet', 3, 'Secondary', 'Knowledge', 'Close', 'd6+4 phy', 'One-Handed', 'Charged', 'Mark a Stress to gain a +1 bonus to your Proficiency on a primary weapon attack.'),
  ('war-dart', 'War Dart', 3, 'Secondary', 'Agility', 'Far', 'd6+5 phy', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Agility, Melee, d8+5.'),
  ('hand-sling', 'Hand Sling', 3, 'Secondary', 'Finesse', 'Very Far', 'd6+4 phy', 'One-Handed', 'Versatile', 'This weapon can also be used with these statistics—Finesse, Close, d8+4.'),
  ('legendary-hatchet', 'Legendary Hatchet', 4, 'Secondary', 'Agility', 'Melee', 'd8+6 phy', 'One-Handed', 'Follow-Up', 'On a successful attack with your primary weapon within Melee range, you can mark a Stress to gain a +1 bonus to your Proficiency for this attack.'),
  ('legendary-shortsword', 'Legendary Shortsword', 4, 'Secondary', 'Agility', 'Melee', 'd8+6 phy', 'One-Handed', 'Paired', '+5 to primary weapon damage to targets within Melee range'),
  ('legendary-offhand-brass-knuckles', 'Legendary Offhand Brass Knuckles', 4, 'Secondary', 'Strength', 'Melee', 'd8+6 phy', 'One-Handed', 'Paired', '+5 to primary weapon damage to targets within Melee range'),
  ('legendary-round-shield', 'Legendary Round Shield', 4, 'Secondary', 'Strength', 'Melee', 'd4+6 phy', 'One-Handed', 'Protective', '+4 to Armor Score'),
  ('legendary-tower-shield', 'Legendary Tower Shield', 4, 'Secondary', 'Strength', 'Melee', 'd6+6 phy', 'One-Handed', 'Barrier', '+5 to Armor Score; −1 to Evasion.'),
  ('legendary-small-dagger', 'Legendary Small Dagger', 4, 'Secondary', 'Finesse', 'Melee', 'd8+6 phy', 'One-Handed', 'Paired', '+5 to primary weapon damage to targets within Melee range'),
  ('legendary-throwing-knives', 'Legendary Throwing Knives', 4, 'Secondary', 'Finesse', 'Melee', 'd8+6 phy', 'One-Handed', 'Stockpiled', 'You can throw this weapon within Close range by making an attack roll using Finesse. You don’t have to retrieve it, as you always have another on hand.'),
  ('legendary-fighting-cloak', 'Legendary Fighting Cloak', 4, 'Secondary', 'Presence', 'Melee', 'd4+6 phy', 'One-Handed', 'Padded', '+5 to damage thresholds'),
  ('legendary-rune-shield', 'Legendary Rune Shield', 4, 'Secondary', 'Knowledge', 'Melee', 'd4+6 mag', 'One-Handed', 'Protective', '+4 to Armor Score'),
  ('legendary-focus-runes', 'Legendary Focus Runes', 4, 'Secondary', 'Instinct', 'Very Close', 'd6+6 mag', 'One-Handed', 'Focused', '+1 to primary weapon damage to targets within Very Close range'),
  ('legendary-whip', 'Legendary Whip', 4, 'Secondary', 'Presence', 'Very Close', 'd6+6 phy', 'One-Handed', 'Startling', 'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'),
  ('legendary-grappler', 'Legendary Grappler', 4, 'Secondary', 'Finesse', 'Close', 'd6+6 phy', 'One-Handed', 'Hooked', 'On a successful attack, you can pull the target into Melee range.'),
  ('legendary-hand-crossbow', 'Legendary Hand Crossbow', 4, 'Secondary', 'Finesse', 'Far', 'd6+7 phy', 'One-Handed', null, null),
  ('braveshield', 'Braveshield', 4, 'Secondary', 'Agility', 'Melee', 'd4+6 phy', 'One-Handed', 'Sheltering', 'When you mark an Armor Slot, it reduces damage for you and all allies within Melee range of you who took the same damage.'),
  ('knuckle-claws', 'Knuckle Claws', 4, 'Secondary', 'Strength', 'Melee', 'd6+8 phy', 'One-Handed', 'Doubled Up', 'When you make an attack with your primary weapon, you can deal damage to another target within Melee range.'),
  ('void-needle', 'Void Needle', 4, 'Secondary', 'Finesse', 'Melee', 'd4+6 phy', 'One-Handed', 'Inverted', 'When you roll a weapon attack with Fear, you gain a Hope.'),
  ('echo-blade', 'Echo Blade', 4, 'Secondary', 'Presence', 'Melee', 'd4+6 mag', 'One-Handed', 'Doubled Up', 'When you succeed on an attack with your primary weapon, you can deal damage to another target within Melee range.'),
  ('mobius-orb', 'Möbius Orb', 4, 'Secondary', 'Knowledge', 'Melee', 'd8+6 mag', 'One-Handed', 'Recursive', 'When you roll the maximum value on a damage die, roll an additional damage die and add the result to the total damage. This feature can trigger repeatedly.'),
  ('primer-shard', 'Primer Shard', 4, 'Secondary', 'Instinct', 'Very Close', 'd4 phy', 'One-Handed', 'Locked On', 'On a successful attack, your next attack against the same target with your primary weapon automatically succeeds.'),
  ('blackblood-tendril', 'Blackblood Tendril', 4, 'Secondary', 'Instinct', 'Close', 'd6+8 mag', 'One-Handed', 'Poisonous', 'When a target marks any number of Hit Points from an attack you rolled with Fear, they mark an equal number of Stress.'),
  ('light-frame-wheelchair', 'Light-Frame Wheelchair', 1, 'Primary', 'Agility', 'Melee', 'd8 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('improved-light-frame-wheelchair', 'Improved Light-Frame Wheelchair', 2, 'Primary', 'Agility', 'Melee', 'd8+3 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('advanced-light-frame-wheelchair', 'Advanced Light-Frame Wheelchair', 3, 'Primary', 'Agility', 'Melee', 'd8+6 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('legendary-light-frame-wheelchair', 'Legendary Light-Frame Wheelchair', 4, 'Primary', 'Agility', 'Melee', 'd8+9 phy', 'One-Handed', 'Quick', 'When you make an attack, you can mark a Stress to target another creature within range.'),
  ('heavy-frame-wheelchair', 'Heavy-Frame Wheelchair', 1, 'Primary', 'Strength', 'Melee', 'd12+3 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('improved-heavy-frame-wheelchair', 'Improved Heavy-Frame Wheelchair', 2, 'Primary', 'Strength', 'Melee', 'd12+6 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('advanced-heavy-frame-wheelchair', 'Advanced Heavy-Frame Wheelchair', 3, 'Primary', 'Strength', 'Melee', 'd12+9 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('legendary-heavy-frame-wheelchair', 'Legendary Heavy-Frame Wheelchair', 4, 'Primary', 'Strength', 'Melee', 'd12+12 phy', 'Two-Handed', 'Heavy', '−1 to Evasion'),
  ('arcane-frame-wheelchair', 'Arcane-Frame Wheelchair', 1, 'Primary', 'Spellcast', 'Far', 'd6 mag', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('improved-arcane-frame-wheelchair', 'Improved Arcane-Frame Wheelchair', 2, 'Primary', 'Spellcast', 'Far', 'd6+3 mag', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('advanced-arcane-frame-wheelchair', 'Advanced Arcane-Frame Wheelchair', 3, 'Primary', 'Spellcast', 'Far', 'd6+6 mag', 'One-Handed', 'Reliable', '+1 to attack rolls'),
  ('legendary-arcane-frame-wheelchair', 'Legendary Arcane-Frame Wheelchair', 4, 'Primary', 'Spellcast', 'Far', 'd6+9 mag', 'One-Handed', 'Reliable', '+1 to attack rolls')
on conflict (slug) do update set
  name = excluded.name,
  tier = excluded.tier,
  weapon_type = excluded.weapon_type,
  trait = excluded.trait,
  range = excluded.range,
  damage = excluded.damage,
  burden = excluded.burden,
  feature_name = excluded.feature_name,
  feature_description = excluded.feature_description;

-- Slugs present in the original seed file but not produced from this SRD
-- (removed in the new SRD; rows left untouched, review manually):
--   axe-of-fortunis
--   blessed-anlace
--   firestaff
--   ghostblade
--   gilded-bow
--   ilmari-s-rifle
--   mage-orb
--   runes-of-ruination
--   widgast-pendant
