-- Generated from the Daggerheart SRD (srd.pdf) by scripts run on 2026-09-05.
-- Upserts keyed on slug: existing rows are updated in place (ids are preserved),
-- new rows are inserted. Rows whose slug no longer appears in the SRD are left
-- untouched and listed at the bottom of this file.
--
-- Run order: 01_domains, 02_subclasses, 03_classes, 04_ancestries, 05_communities,
--            06_abilities, 07_weapons, 08_armors, 09_items, 10_consumables

insert into public.armors
  (slug, name, tier, base_threshold_low, base_threshold_high, base_score, feature_name, feature_description)
values
  ('mage-robes', 'Mage Robes', 1, 4, 10, 2, 'Enchanted', 'Gain a bonus to your damage thresholds equal to your Spellcast trait.'),
  ('gambeson-armor', 'Gambeson Armor', 1, 5, 11, 3, 'Flexible', '+1 to Evasion'),
  ('brigandine-armor', 'Brigandine Armor', 1, 6, 12, 3, 'Lined', 'Mark a Stress to negate Minor damage.'),
  ('leather-armor', 'Leather Armor', 1, 6, 13, 3, null, null),
  ('scale-mail-armor', 'Scale Mail Armor', 1, 7, 14, 3, 'Cumbersome', '−1 to Finesse'),
  ('chainmail-armor', 'Chainmail Armor', 1, 7, 15, 4, 'Heavy', '−1 to Evasion'),
  ('banded-armor', 'Banded Armor', 1, 8, 16, 4, 'Bulky', '−1 to Evasion; when you take Severe damage, you must mark a Stress.'),
  ('full-plate-armor', 'Full Plate Armor', 1, 8, 17, 4, 'Very Heavy', '−2 to Evasion; −1 to Agility'),
  ('improved-mage-robes', 'Improved Mage Robes', 2, 6, 15, 3, 'Enchanted', 'Gain a bonus to your damage thresholds equal to your Spellcast trait.'),
  ('improved-gambeson-armor', 'Improved Gambeson Armor', 2, 7, 16, 4, 'Flexible', '+1 to Evasion'),
  ('improved-brigandine-armor', 'Improved Brigandine Armor', 2, 9, 19, 4, 'Lined', 'Mark a Stress to negate Minor damage.'),
  ('improved-leather-armor', 'Improved Leather Armor', 2, 9, 20, 4, null, null),
  ('improved-scale-mail-armor', 'Improved Scale Mail Armor', 2, 11, 23, 4, 'Cumbersome', '−1 to Finesse'),
  ('improved-chainmail-armor', 'Improved Chainmail Armor', 2, 11, 24, 5, 'Heavy', '−1 to Evasion'),
  ('improved-banded-armor', 'Improved Banded Armor', 2, 13, 27, 5, 'Bulky', '−1 to Evasion; when you take Severe damage, you must mark a Stress.'),
  ('improved-full-plate-armor', 'Improved Full Plate Armor', 2, 13, 28, 5, 'Very Heavy', '−2 to Evasion; −1 to Agility'),
  ('enchanters-robes', 'Enchanter’s Robes', 2, 9, 20, 4, 'Mnemonic', 'Once per scene, you can recall a domain card from your vault without paying its Recall Cost.'),
  ('hawkguards-mantle', 'Hawkguard’s Mantle', 2, 9, 20, 4, 'Gliding', 'You can glide up to Far range and are immune to damage from falling.'),
  ('spidersilk-tunic', 'Spidersilk Tunic', 2, 9, 20, 4, 'Wall-Crawling', '+1 Evasion; you can walk on walls as easily as on the ground.'),
  ('stormthread-habit', 'Stormthread Habit', 2, 9, 20, 4, 'Absorbing', 'Once per scene when you take magic damage, you can clear an Armor Slot.'),
  ('elundrian-chain-armor', 'Elundrian Chain Armor', 2, 9, 21, 4, 'Warded', 'You reduce incoming magic damage by your Armor Score before applying it to your damage thresholds.'),
  ('harrowbone-armor', 'Harrowbone Armor', 2, 9, 21, 4, 'Resilient', 'Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot.'),
  ('irontree-breastplate-armor', 'Irontree Breastplate Armor', 2, 9, 20, 4, 'Reinforced', 'When you mark your last Armor Slot, increase your damage thresholds by +2 until you clear at least 1 Armor Slot.'),
  ('runetan-floating-armor', 'Runetan Floating Armor', 2, 9, 20, 4, 'Shifting', 'When you are targeted for an attack, you can mark an Armor Slot to give the attack roll against you disadvantage.'),
  ('tyris-soft-armor', 'Tyris Soft Armor', 2, 8, 18, 5, 'Quiet', 'You gain a +2 bonus to rolls you make to move silently.'),
  ('wyrdwood-splint-armor', 'Wyrdwood Splint Armor', 2, 10, 21, 5, 'Quick-Striding', 'You can’t be Restrained and can move up to Far range as part of an action roll.'),
  ('rosewild-armor', 'Rosewild Armor', 2, 11, 23, 5, 'Hopeful', 'When you would spend a Hope, you can mark an Armor Slot instead.'),
  ('trollhide-cuirass', 'Trollhide Cuirass', 2, 11, 23, 5, 'Self-Healing', 'When you take a rest, clear an Armor Slot.'),
  ('gilded-sunplate', 'Gilded Sunplate', 2, 12, 26, 5, 'Resplendent', 'Once per scene when you spend Hope, you can clear an Armor Slot.'),
  ('advanced-mage-robes', 'Advanced Mage Robes', 3, 8, 22, 4, 'Enchanted', 'Gain a bonus to your damage thresholds equal to your Spellcast trait.'),
  ('advanced-gambeson-armor', 'Advanced Gambeson Armor', 3, 9, 23, 5, 'Flexible', '+1 to Evasion'),
  ('advanced-brigandine-armor', 'Advanced Brigandine Armor', 3, 11, 26, 5, 'Lined', 'Mark a Stress to negate Minor damage.'),
  ('advanced-leather-armor', 'Advanced Leather Armor', 3, 11, 27, 5, null, null),
  ('advanced-scale-mail-armor', 'Advanced Scale Mail Armor', 3, 13, 30, 5, 'Cumbersome', '−1 to Finesse'),
  ('advanced-chainmail-armor', 'Advanced Chainmail Armor', 3, 13, 31, 6, 'Heavy', '−1 to Evasion'),
  ('advanced-banded-armor', 'Advanced Banded Armor', 3, 15, 34, 6, 'Bulky', '−1 to Evasion; when you take Severe damage, you must mark a Stress.'),
  ('advanced-full-plate-armor', 'Advanced Full Plate Armor', 3, 15, 35, 6, 'Very Heavy', '−2 to Evasion; −1 to Agility'),
  ('granminsters-finery', 'Granminster’s Finery', 3, 11, 27, 2, 'Magnificent', 'Gain a bonus to your Armor Score equal to your Presence.'),
  ('spiked-plate-armor', 'Spiked Plate Armor', 3, 10, 25, 5, 'Sharp', 'On a successful attack against a target within Melee range, add a d4 to the damage roll.'),
  ('astral-raiment', 'Astral Raiment', 3, 11, 27, 5, 'Stellar', 'Mark a Stress to gain advantage on a Spellcast roll.'),
  ('bellamie-fine-armor', 'Bellamoi Fine Armor', 3, 11, 27, 5, 'Gilded', '+1 to Presence'),
  ('cloverweave-cloak', 'Cloverweave Cloak', 3, 11, 27, 5, 'Fortune-Favored', 'Once per scene, you can change a failure with Hope into a success with Fear.'),
  ('dragonscale-armor', 'Dragonscale Armor', 3, 11, 27, 5, 'Impenetrable', 'Once per short rest, when you would mark your last Hit Point, you can instead mark a Stress.'),
  ('skywardens-lamellar', 'Skywarden’s Lamellar', 3, 11, 27, 5, 'Vigilant', '+2 to Evasion'),
  ('bloodstone-plate-armor', 'Bloodstone Plate Armor', 3, 13, 35, 6, 'Bloodthirsty', 'When you critically succeed on a weapon attack within Melee range, clear a Hit Point.'),
  ('deep-forged-coral-armor', 'Deep-Forged Coral Armor', 3, 13, 35, 6, 'Aquatic', 'You can breathe underwater and gain advantage on Agility Rolls while submerged.'),
  ('bladefare-armor', 'Bladefare Armor', 3, 16, 39, 6, 'Physical', 'You can’t mark an Armor Slot to reduce magic damage.'),
  ('monetts-cloak', 'Monett’s Cloak', 3, 16, 39, 6, 'Magic', 'You can’t mark an Armor Slot to reduce physical damage.'),
  ('runes-of-fortification', 'Runes of Fortification', 3, 17, 43, 6, 'Painful', 'Each time you mark an Armor Slot, you must mark a Stress.'),
  ('legendary-mage-robes', 'Legendary Mage Robes', 4, 10, 31, 5, 'Enchanted', 'Gain a bonus to your damage thresholds equal to your Spellcast trait.'),
  ('legendary-gambeson-armor', 'Legendary Gambeson Armor', 4, 11, 32, 6, 'Flexible', '+1 to Evasion'),
  ('legendary-brigandine-armor', 'Legendary Brigandine Armor', 4, 13, 35, 6, 'Lined', 'Mark a Stress to negate Minor damage.'),
  ('legendary-leather-armor', 'Legendary Leather Armor', 4, 13, 36, 6, null, null),
  ('legendary-scale-mail-armor', 'Legendary Scale Mail Armor', 4, 15, 39, 6, 'Cumbersome', '−1 to Finesse'),
  ('legendary-chainmail-armor', 'Legendary Chainmail Armor', 4, 15, 40, 7, 'Heavy', '−1 to Evasion'),
  ('legendary-banded-armor', 'Legendary Banded Armor', 4, 17, 43, 7, 'Bulky', '−1 to Evasion; when you take Severe damage, you must mark a Stress.'),
  ('legendary-full-plate-armor', 'Legendary Full Plate Armor', 4, 17, 44, 7, 'Very Heavy', '−2 to Evasion; −1 to Agility'),
  ('full-fortified-armor', 'Full Fortified Armor', 4, 15, 40, 4, 'Fortified', 'When you mark an Armor Slot, you reduce the severity of an attack by two thresholds instead of one.'),
  ('channeling-armor', 'Channeling Armor', 4, 13, 36, 5, 'Channeling', '+1 to Spellcast Rolls'),
  ('darkweave-shroud', 'Darkweave Shroud', 4, 13, 36, 5, 'Ghostwalker', 'Once per rest, mark a Stress to move up to Close range through solid objects.'),
  ('emberwoven-armor', 'Emberwoven Armor', 4, 13, 36, 6, 'Burning', 'When an adversary attacks you within Melee range, they mark a Stress.'),
  ('godbound-laminar', 'Godbound Laminar', 4, 13, 36, 6, 'Divine', 'When you mark an Armor Slot, gain a Hope.'),
  ('veritas-opal-armor', 'Veritas Opal Armor', 4, 13, 36, 6, 'Truthseeking', 'This armor glows when another creature within Close range tells a lie.'),
  ('circle-forged-dreadplate', 'Circle-Forged Dreadplate', 4, 14, 38, 6, 'Accursed', 'When you mark any number of Hit Points from an attack, roll a d4. On a result of 4, the attacker must mark an equal number of Stress.'),
  ('rune-forged-exosuit', 'Rune-Forged Exosuit', 4, 12, 39, 7, 'Attuned', 'The maximum number of domain cards in your loadout is reduced by one, but you gain a bonus to your damage thresholds equal to your tier.'),
  ('dunamis-silkchain', 'Dunamis Silkchain', 4, 13, 36, 7, 'Timeslowing', 'Mark an Armor Slot to roll a d4 and add its result as a bonus to your Evasion against an incoming attack.'),
  ('hallowed-heroplate', 'Hallowed Heroplate', 4, 13, 35, 7, 'Blessed', 'Once per long rest, you can spend any number of Hope before you make the Risk It All death move. You gain a bonus to the result of your Hope Die equal to the number of Hope spent.'),
  ('resonant-harness', 'Resonant Harness', 4, 15, 40, 7, 'Vitreous', 'When you would take Severe or greater damage, you can mark 2 Armor Slots to negate that damage. If you do, you gain a −5 penalty to your damage thresholds until you choose to repair your armor as a downtime move.'),
  ('savior-chainmail', 'Savior Chainmail', 4, 18, 48, 8, 'Difficult', '−1 to all character traits and Evasion')
on conflict (slug) do update set
  name = excluded.name,
  tier = excluded.tier,
  base_threshold_low = excluded.base_threshold_low,
  base_threshold_high = excluded.base_threshold_high,
  base_score = excluded.base_score,
  feature_name = excluded.feature_name,
  feature_description = excluded.feature_description;

-- Renamed in this SRD; the existing slug is kept so character references stay intact:
--   bellamie-fine-armor  ->  Bellamoi Fine Armor
