-- Generated from the Daggerheart SRD (srd.pdf) by scripts run on 2026-09-05.
-- Upserts keyed on slug: existing rows are updated in place (ids are preserved),
-- new rows are inserted. Rows whose slug no longer appears in the SRD are left
-- untouched and listed at the bottom of this file.
--
-- Run order: 01_domains, 02_subclasses, 03_classes, 04_ancestries, 05_communities,
--            06_abilities, 07_weapons, 08_armors, 09_items, 10_consumables

-- Core Set consumables plus the Hope & Fear Expansion Set consumables.

insert into public.consumables
  (slug, name, description)
values
  ('stride-potion', 'Stride Potion', 'You gain a +1 bonus to your next Agility Roll.'),
  ('bolster-potion', 'Bolster Potion', 'You gain a +1 bonus to your next Strength Roll.'),
  ('control-potion', 'Control Potion', 'You gain a +1 bonus to your next Finesse Roll.'),
  ('attune-potion', 'Attune Potion', 'You gain a +1 bonus to your next Instinct Roll.'),
  ('charm-potion', 'Charm Potion', 'You gain a +1 bonus to your next Presence Roll.'),
  ('enlighten-potion', 'Enlighten Potion', 'You gain a +1 bonus to your next Knowledge Roll.'),
  ('minor-health-potion', 'Minor Health Potion', 'Clear 1d4 HP.'),
  ('minor-stamina-potion', 'Minor Stamina Potion', 'Clear 1d4 Stress.'),
  ('grindeltooth-venom', 'Grindletooth Venom', 'You can apply this venom to a weapon that deals physical damage to add a d6 to your next damage roll with that weapon.'),
  ('varik-leaves', 'Varik Leaves', 'You can eat these paired leaves to immediately gain 2 Hope.'),
  ('vial-of-moondrip', 'Vial of Moondrip', 'When you drink the contents of this vial, you can see in total darkness until your next rest.'),
  ('unstable-arcane-shard', 'Unstable Arcane Shard', 'You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 1d20 magic damage.'),
  ('potion-of-stability', 'Potion of Stability', 'You can drink this potion to choose one additional downtime move.'),
  ('improved-grindeltooth-venom', 'Improved Grindletooth Venom', 'You can apply this venom to a weapon that deals physical damage to add a d8 to your next damage roll with that weapon.'),
  ('morphing-clay', 'Morphing Clay', 'You can spend a Hope to use this clay, altering your face enough to make you unrecognizable until your next rest.'),
  ('vial-of-darksmoke', 'Vial of Darksmoke', 'When an adversary attacks you, use this vial and roll a number of d6s equal to your Agility. Add the highest result to your Evasion against the attack.'),
  ('jumping-root', 'Jumping Root', 'Eat this root to leap up to Far range once without needing to roll.'),
  ('snap-powder', 'Snap Powder', 'Mark a Stress and clear a HP.'),
  ('health-potion', 'Health Potion', 'Clear 1d4+1 HP.'),
  ('stamina-potion', 'Stamina Potion', 'Clear 1d4+1 Stress.'),
  ('armor-stitcher', 'Armor Stitcher', 'You can use this stitcher to spend any number of Hope and clear that many Armor Slots.'),
  ('gill-salve', 'Gill Salve', 'You can apply this salve to your neck to breathe underwater for a number of minutes equal to your level.'),
  ('replication-parchment', 'Replication Parchment', 'By touching this piece of parchment to another, you can perfectly copy the second parchment’s contents. Once used, this parchment becomes mundane paper.'),
  ('improved-arcane-shard', 'Improved Arcane Shard', 'You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 2d20 magic damage.'),
  ('major-stride-potion', 'Major Stride Potion', 'You gain a +1 bonus to your Agility until your next rest.'),
  ('major-bolster-potion', 'Major Bolster Potion', 'You gain a +1 bonus to your Strength until your next rest.'),
  ('major-control-potion', 'Major Control Potion', 'You gain a +1 bonus to your Finesse until your next rest.'),
  ('major-attune-potion', 'Major Attune Potion', 'You gain a +1 bonus to your Instinct until your next rest.'),
  ('major-charm-potion', 'Major Charm Potion', 'You gain a +1 bonus to your Presence until your next rest.'),
  ('major-enlighten-potion', 'Major Enlighten Potion', 'You gain a +1 bonus to your Knowledge until your next rest.'),
  ('blood-of-the-yorgi', 'Blood of the Yorgi', 'You can drink this blood to disappear from where you are and immediately reappear at a point you can see within Very Far range.'),
  ('hornets-secret-potion', 'Homet’s Secret Potion', 'After drinking this potion, the next successful attack you make critically succeeds.'),
  ('redthorn-saliva', 'Redthorn Saliva', 'You can apply this saliva to a weapon that deals physical damage to add a d12 to your next damage roll with that weapon.'),
  ('channelstone', 'Channelstone', 'You can use this stone to take a spell or grimoire from your vault, use it once, and return it to your vault.'),
  ('mythic-dust', 'Mythic Dust', 'You can apply this dust to a weapon that deals magic damage to add a d12 to your next damage roll with that weapon.'),
  ('acidpaste', 'Acidpaste', 'This paste eats away walls and other surfaces in bright flashes.'),
  ('hopehold-flare', 'Hopehold Flare', 'When you use this flare, allies within Close range roll a d6 when they spend a Hope. On a result of 6, they gain the effect of that Hope without spending it. The flare lasts until the end of the scene.'),
  ('major-arcane-shard', 'Major Arcane Shard', 'You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 4d20 magic damage.'),
  ('featherbone', 'Featherbone', 'You can use this bone to control your falling speed for a number of minutes equal to your level.'),
  ('circle-of-the-void', 'Circle of the Void', 'Mark a Stress to create a void that extends up to Far range. No magic can be cast inside the void, and creatures within the void are immune to magic damage.'),
  ('sun-tree-sap', 'Sun Tree Sap', 'Consume this sap to roll a d6. On a result of 5–6, clear 2 HP. On a result of 2–4, clear 3 Stress. On a result of 1, see through the veil of death and return changed, gaining one scar.'),
  ('dripfang-poison', 'Dripfang Poison', 'A creature who consumes this poison takes 8d10 direct magic damage.'),
  ('major-health-potion', 'Major Health Potion', 'Clear 1d4+2 HP.'),
  ('major-stamina-potion', 'Major Stamina Potion', 'Clear 1d4+2 Stress.'),
  ('ogre-musk', 'Ogre Musk', 'You can use this musk to prevent anyone from tracking you by mundane or magical means until your next rest.'),
  ('wingsprout', 'Wingsprout', 'You gain magic wings that allow you to fly for a number of minutes equal to your level.'),
  ('jar-of-lost-voices', 'Jar of Lost Voices', 'You can open this jar to release a deafening echo of voices for a number of minutes equal to your Instinct. Creatures within Far range unprepared for the sound take 6d8 magic damage.'),
  ('dragonbloom-tea', 'Dragonbloom Tea', 'You can drink this tea to unleash a fiery breath attack. Make an Instinct Roll against all adversaries in front of you within Close range. Targets you succeed against take d20 physical damage using your Proficiency.'),
  ('bridge-seed', 'Bridge Seed', 'Thick vines grow from your location to a point of your choice within Far range, allowing you to climb up or across them. The vines dissipate on your next short rest.'),
  ('sleeping-sap', 'Sleeping Sap', 'You can drink this potion to fall asleep for a full night’s rest. You clear all Stress upon waking.'),
  ('feast-of-xurla', 'Feast of Xuria', 'You can eat this meal to clear all HP and Stress and gain 1d4 Hope.'),
  ('bonding-honey', 'Bonding Honey', 'This honey can be used to glue two objects together permanently.'),
  ('shrinking-potion', 'Shrinking Potion', 'You can drink this potion to halve your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Agility and a −1 penalty to your Proficiency.'),
  ('growing-potion', 'Growing Potion', 'You can drink this potion to double your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Strength and a +1 bonus to your Proficiency.'),
  ('knowledge-stone', 'Knowledge Stone', 'If you die while holding this stone, an ally can take a card from your loadout to place in their loadout or vault. After they take this knowledge, the stone crumbles.'),
  ('sweet-moss', 'Sweet Moss', 'You can consume this moss during a rest to clear 1d10 HP or 1d10 Stress.'),
  ('blinding-orb', 'Blinding Orb', 'You can activate this orb to create a flash of bright light. All targets within Close range become Vulnerable until they mark HP.'),
  ('death-tea', 'Death Tea', 'After you drink this tea, you instantly kill your target when you critically succeed on an attack. If you don’t critically succeed on an attack before your next long rest, you die.'),
  ('mirror-of-marigold', 'Mirror of Marigold', 'When you take damage, you can spend a Hope to negate that damage, after which the mirror shatters.'),
  ('stardrop', 'Stardrop', 'You can use this stardrop to summon a hailstorm of comets that deals 8d20 physical damage to all targets within Very Far range.'),
  ('warding-candle', 'Warding Candle', 'You can light this candle to fill an area within Close range with a halo of light. A creature outside the halo can’t enter it if they have ill intent toward a creature within it. The candle burns for an hour.'),
  ('iridian-dust', 'Iridian Dust', 'This multicolored powder sticks to everything and prevents creatures covered in it from becoming Hidden.'),
  ('verglasian-seed', 'Verglasian Seed', 'You can use this ice shard to instantly freeze an area of water up to Close range.'),
  ('cupbearers-bezoar', 'Cupbearer’s Bezoar', 'You can swallow this bezoar to become immune to poisons until your next long rest.'),
  ('mossmantle-potion', 'Mossmantle Potion', 'You can drink this tea to perfectly blend into natural environments until your next rest.'),
  ('lyrebird-lozenge', 'Lyrebird Lozenge', 'You can dissolve this lozenge in your mouth to perfectly mimic any voice you’ve heard until the end of the scene.'),
  ('vial-of-featherfall', 'Vial of Featherfall', 'You can drink this potion to ignore damage from falling for the next 10 minutes.'),
  ('chimeric-saliva', 'Chimeric Saliva', 'You can apply this saliva to a weapon that deals physical damage to change its damage type to magic until your next rest.'),
  ('packet-of-space-dust', 'Packet of Space Dust', 'This dust causes anything it covers to become lighter than air. One packet contains enough dust to cover the contents of a picnic basket, and the effects last for an hour.'),
  ('pipeweed', 'Pipeweed', 'When you choose the Clear Stress downtime move during a short rest, you can smoke this non-intoxicating leaf to clear an additional Stress. Any other PCs who chose the Clear Stress downtime move also gain this benefit.'),
  ('deathseers-powder', 'Deathseer’s Powder', 'You can sprinkle this powder over a recently deceased corpse to conjure a spectral reprise of their final minute of life.'),
  ('slayers-salt', 'Slayer’s Salt', 'You can spread this salt in a line along windowsills or thresholds to create a magical barrier that undead creatures can’t cross until the line is broken.'),
  ('yakamel-milk', 'Yakamel Milk', 'After consuming this milk, the next time you clear 1 or more Hit Points, you clear an additional Hit Point.'),
  ('glowmoss-mushroom', 'Glowmoss Mushroom', 'You can break this mushroom into pieces, causing it to glow bright blue until your next long rest.'),
  ('red-ooze-oil', 'Red Ooze Oil', 'You can coat your weapon in this oil. The next successful attack you make with this weapon deals an extra 1d8 magic damage and temporarily Ignites the target. While Ignited, the target takes 1d4 magic damage when they take the spotlight.'),
  ('instant-camp', 'Instant Camp', 'You can unfold this small mechanical box into a camping tent large enough to safely house six people. The tent collapses at the end of your next long rest.'),
  ('bundle-of-spiderlegs', 'Bundle of Spiderlegs', 'You can eat these spiderlegs to walk on walls until your next rest.'),
  ('ciscan-fog-bottle', 'Ciscan Fog Bottle', 'You can break this jar to fill the area within Close range with magical mist. A creature who enters the mist clears a Stress and becomes Hidden.'),
  ('snapthorn-seed', 'Snapthorn Seed', 'You can throw this seed at a point you can see. It explodes into a tangle of binding vines that temporarily Restrains all creatures within Close range of that point.'),
  ('sprite-bottle', 'Sprite Bottle', 'When you mark your last Hit Point, this bottle shatters to release the Sprite inside. The Sprite clears all your Hit Points before fading from the Mortal Realm.'),
  ('gravity-bomb', 'Gravity Bomb', 'You can throw this peach-sized mechanical orb at a point within Far range. It implodes and pulls all creatures and objects within Close range of that point into Melee range with it.'),
  ('gossip-flower', 'Gossip Flower', 'You can plant this seed in soil. It instantly grows into a small flower that records everything it hears for up to one week. When plucked, the flower recites what it recorded in real time, then withers.'),
  ('displacement-token', 'Displacement Token', 'You can swallow this token to conjure two illusions of yourself that you can control. Each illusion lasts until it takes damage or until your next rest.'),
  ('night-hags-dust', 'Night Hag’s Dust', 'You can blow this dust in an adversary’s face to prevent them from clearing Stress until your next long rest.'),
  ('self-sewing-thread', 'Self-Sewing Thread', 'You can use this thread to clear either a Hit Point or 2 Armor Slots.'),
  ('stonemasons-fortune', 'Stonemason’s Fortune', 'When you throw this gray brick on the ground, it immediately grows into a 6-foot-tall, 10-foot-wide, and 2-foot-deep wall of solid stone.'),
  ('mnemonic-potion', 'Mnemonic Potion', 'You can drink this potion to Utilize an Experience without spending a Hope.'),
  ('salamander-salve', 'Salamander Salve', 'You can apply this salve to your skin to make yourself immune to heat until your next rest.'),
  ('green-ooze-oil', 'Green Ooze Oil', 'You can coat your weapon in this oil. The next successful attack you make with this weapon deals an extra 1d8 magic damage and temporarily Corrodes the target. While Corroded, the target gains a −2 penalty to their damage thresholds.'),
  ('sunlight-orb', 'Sunlight Orb', 'You can shatter this orb to make the area within Very Far range appear as though it’s sunlit daytime for the next 24 hours.'),
  ('moonlight-orb', 'Moonlight Orb', 'You can shatter this orb to make the area within Very Far range appear as though it’s moonlit nighttime for the next 24 hours.'),
  ('midas-flask', 'Midas Flask', 'You can pour this small flask of alchemical liquid over a mundane item to instantly transmute it into a handful of gold.'),
  ('staff-of-reversal', 'Staff of Reversal', 'You can break this staff against the ground to reverse one magical transformation or effect within Far range.'),
  ('berserkers-brew', 'Berserker’s Brew', 'When you drink this dram of liquid, you gain a bonus to your Strength and a penalty to your Finesse and Knowledge equal to your Instinct (minimum 1). This effect lasts until you make a death move or until your next rest.'),
  ('emberite-shard', 'Emberite Shard', 'Choose a point within Far range. All targets within Close range of that point must succeed on a Reaction Roll (16) or take 3d6 magic damage and become temporarily Ablaze. While Ablaze, a creature must roll a d4 whenever they make an action roll. On a result of 1, they mark a Hit Point. On a result of 4, they clear the Ablaze condition.'),
  ('arcticite-shard', 'Arcticite Shard', 'Choose a point within Far range. All targets within Close range of that point must succeed on a Reaction Roll (16) or take 3d6 magic damage and become temporarily Restrained by ice.'),
  ('fulgurite-shard', 'Fulgurite Shard', 'Choose a point within Far range. All targets within Close range of that point must succeed on a Reaction Roll (16) or take 3d6 magic damage and mark 1d4 Stress as lightning crackles through the area.'),
  ('demiurges-draught', 'Demiurge’s Draught', 'You can drink this draught to gain a +1 bonus to your Proficiency for your next successful attack roll.'),
  ('cockerel-claw-tea', 'Cockerel Claw Tea', 'You can drink this tea to refresh your features as if you had taken a long rest.'),
  ('potion-of-vigilance', 'Potion of Vigilance', 'You can drink this potion to gain a +1 bonus to your Evasion until you mark a Hit Point.'),
  ('cacophonous-concoction', 'Cacophonous Concoction', 'When you drink this potion, anything you say or do in the next hour becomes impossible for a witness to recount. Any attempts they make to communicate what they saw, heard, or otherwise sensed comes out garbled or nonsensical.'),
  ('nightmare-mead', 'Nightmare Mead', 'You can drink this potion to discover the deepest fear of the next person you make eye contact with. When you do, the GM gains a Fear.'),
  ('stake-of-abjuration', 'Stake of Abjuration', 'You can hammer this stake into the ground and make a proclamation. Until your next rest, a creature within Far range of the stake who transgresses that proclamation must mark a Stress. The stake lasts until your next rest, then it shatters.'),
  ('psychopomps-shroud', 'Psychopomp’s Shroud', 'You can place this shroud over the corpse of a recently deceased creature. The creature’s spirit enters the shroud and becomes your spectral assistant until the next sunrise, when they pass through the veil of death and take the shroud with them.'),
  ('phial-of-deep-ink', 'Phial of Deep Ink', 'You can drink this bottle of ink to transform into a cephalopod of roughly your size for the next hour. You gain rubbery skin, soft bones, the ability to breathe underwater, and new limbs until you have eight total.'),
  ('mesmers-tonic', 'Mesmer’s Tonic', 'When you drink this tonic, the only thing you can hear until your next rest are the surface thoughts of creatures within Very Close range.'),
  ('invisibility-potion', 'Invisibility Potion', 'You are Hidden until you deal damage to another creature or until your next rest.'),
  ('formoid-serum', 'Formoid Serum', 'You can drink this potion to become a swarm of 16 million ants until the end of the scene. You keep and have access to all equipment, loot, and features.'),
  ('steelskin-salve', 'Steelskin Salve', 'You can apply this salve to your skin to gain a bonus to your damage thresholds equal to your tier until the end of the scene.'),
  ('godlings-pomelo', 'Godling’s Pomelo', 'You can eat this citrus fruit to clear all Hit Points and Stress.'),
  ('snakeskin-spirit', 'Snakeskin Spirit', 'You can drink this potion to slough off your outer layer of skin and heal a scar.'),
  ('magic-users-malison', 'Magic-User’s Malison', 'When you release this spellcaster’s trapped soul, you can cast one spell from a card in your vault as if it were in your loadout. This doesn’t work for permanently vaulted cards.'),
  ('quintessential-severant', 'Quintessential Severant', 'You can use this magic blade to cut one magical or metaphysical bond, such as an enchantment, contract, magical tether, or divine oath. When you do, the blade shatters.'),
  ('mask-of-the-echoed-self', 'Mask of the Echoed Self', 'You can wear this mask during your next level up to swap the values of any of your traits. When you do, the mask becomes your permanent face.'),
  ('necroprancers-bell', 'Necroprancer’s Bell', 'You can break this rusted, clapperless bell against the ground to summon a skeletal steed that climbs out of the earth and serves you until the next sunrise.'),
  ('drakemantle', 'Drakemantle', 'You can use this enchanted ancient dragon hide to gain draconic characteristics until the end of the scene, when the hide falls aways in tatters. Until then, you can fly and gain a +5 bonus to your damage thresholds and a +1 bonus to your Proficiency.'),
  ('gamblers-fallacy', 'Gambler’s Fallacy', 'You can spend any number of handfuls of gold by placing them into this slotted ceramic jar shaped like a pig. When you throw the jar at a point within Far range, it explodes and deals 1d20 magic damage for each handful of gold spent to all creatures within Close range of that point. All gold within the jar is destroyed.'),
  ('lionheart-tonic', 'Lionheart Tonic', 'You can drink this tonic to gain a +1 bonus to your Proficiency until you roll with Fear.'),
  ('tears-of-the-undying-hero', 'Tears of the Undying Hero', 'When you drink this potion, death can’t touch you until your next long rest. When you would mark your last Hit Point, instead of making a death move, you make one final action roll before falling into a dreamless slumber until an ally chooses the Tend to Wounds downtime move to clear your Hit Points.'),
  ('featherstep-potion', 'Featherstep Potion', 'You can drink this potion to sprout small wings from your ankles that give you a bonus to your Evasion equal to your tier until your next rest.')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description;

-- Renamed in this SRD; the existing slug is kept so character references stay intact:
--   grindeltooth-venom  ->  Grindletooth Venom
--   improved-grindeltooth-venom  ->  Improved Grindletooth Venom
--   hornets-secret-potion  ->  Homet’s Secret Potion
--   feast-of-xurla  ->  Feast of Xuria
