create table public.consumables (
  id bigint generated always as identity primary key,

  slug text not null unique,
  name text not null,

  description text not null,

  created_at timestamptz not null default now()
);
insert into public.consumables (slug, name, description)
values
('acidpaste','Acidpaste','This paste eats away walls and other surfaces in bright flashes.'),
('armor-stitcher','Armor Stitcher','You can use this stitcher to spend any number of Hope and clear that many Armor Slots.'),
('attune-potion','Attune Potion','You gain a +1 bonus to your next Instinct Roll.'),
('blinding-orb','Blinding Orb','Activate to create a flash of bright light. All targets within Close range become Blinded until they mark HP.'),
('blood-of-the-yorgi','Blood of the Yorgi','Drink to disappear and reappear at a visible point within Very Far range.'),
('bolster-potion','Bolster Potion','You gain a +1 bonus to your next Strength Roll.'),
('bonding-honey','Bonding Honey','This honey can be used to glue two objects together permanently.'),
('bridge-seed','Bridge Seed','Vines grow to a chosen point within Far range, allowing climbing. They dissipate on your next short rest.'),
('channelstone','Channelstone','Take a spell or grimoire from your vault, use it once, and return it.'),
('charm-potion','Charm Potion','You gain a +1 bonus to your next Presence Roll.'),
('circle-of-the-void','Circle of the Void','Mark a Stress to create a void up to Far range where no magic functions and creatures are immune to magic damage.'),
('control-potion','Control Potion','You gain a +1 bonus to your next Finesse Roll.'),
('death-tea','Death Tea','Critically succeeding on an attack kills the target; if no crit before next long rest, you die.'),
('dragonbloom-tea','Dragonbloom Tea','Unleash fiery breath; Instinct Roll against Close-range foes dealing 2d20 physical damage.'),
('dripfang-poison','Dripfang Poison','A creature who consumes this takes 2d10 direct magic damage.'),
('enlighten-potion','Enlighten Potion','You gain a +1 bonus to your next Knowledge Roll.'),
('feast-of-xurla','Feast of Xurla','Clear all HP and Stress and gain 1d4 Hope.'),
('featherbone','Featherbone','Control falling speed for minutes equal to your level.'),
('gill-salve','Gill Salve','Breathe underwater for minutes equal to your level.'),
('grindeltooth-venom','Grindeltooth Venom','Apply to a physical weapon to add a d6 to your next damage roll.'),
('growing-potion','Growing Potion','Double size; +2 Strength and +1 Proficiency until rest or dismissal.'),
('health-potion','Health Potion','Clear 1d4+1 HP.'),
('hopehold-flare','Hopehold Flare','Allies within Close range may regain spent Hope on a d6 roll of 6 until scene end.'),
('hornets-secret-potion','Hornet’s Secret Potion','Your next successful attack critically succeeds.'),
('improved-arcane-shard','Improved Arcane Shard','Throw to deal 2d20 magic damage to Far-range adversaries on success.'),
('improved-grindeltooth-venom','Improved Grindeltooth Venom','Apply to a physical weapon to add a d8 to your next damage roll.'),
('jar-of-lost-voices','Jar of Lost Voices','Release voices dealing 6d8 magic damage to unprepared creatures within Far range.'),
('jumping-root','Jumping Root','Leap up to Far range once without rolling.'),
('knowledge-stone','Knowledge Stone','On death, an ally may take a card from your loadout or vault; the stone crumbles.'),
('major-arcane-shard','Major Arcane Shard','Throw to deal 4d20 magic damage to Far-range adversaries on success.'),
('major-attune-potion','Major Attune Potion','Gain +1 Instinct until your next rest.'),
('major-bolster-potion','Major Bolster Potion','Gain +1 Strength until your next rest.'),
('major-charm-potion','Major Charm Potion','Gain +1 Presence until your next rest.'),
('major-control-potion','Major Control Potion','Gain +1 Finesse until your next rest.'),
('major-enlighten-potion','Major Enlighten Potion','Gain +1 Knowledge until your next rest.'),
('major-health-potion','Major Health Potion','Clear 1d4+2 HP.'),
('major-stamina-potion','Major Stamina Potion','Clear 1d4+2 Stress.'),
('major-stride-potion','Major Stride Potion','Gain +1 Agility until your next rest.'),
('minor-health-potion','Minor Health Potion','Clear 1d4 HP.'),
('minor-stamina-potion','Minor Stamina Potion','Clear 1d4 Stress.'),
('mirror-of-marigold','Mirror of Marigold','Spend a Hope to negate damage, then the mirror shatters.'),
('morphing-clay','Morphing Clay','Spend 4 Hope to alter your face until your next rest.'),
('mythic-dust','Mythic Dust','Apply to a magic weapon to add a d12 to your next damage roll.'),
('ogre-musk','Ogre Musk','Prevents tracking by mundane or magical means until your next rest.'),
('potion-of-stability','Potion of Stability','Choose one additional downtime move.'),
('redthorn-saliva','Redthorn Saliva','Apply to a physical weapon to add a d12 to your next damage roll.'),
('replication-parchment','Replication Parchment','Copy another parchment perfectly; becomes mundane after use.'),
('shrinking-potion','Shrinking Potion','Halve size; +2 Agility and –1 Proficiency until rest or dismissal.'),
('sleeping-sap','Sleeping Sap','Fall asleep for a full night’s rest and clear all Stress.'),
('snap-powder','Snap Powder','Mark a Stress and clear a HP.'),
('stamina-potion','Stamina Potion','Clear 1d4+1 Stress.'),
('stardrop','Stardrop','Summon comets dealing 8d20 physical damage within Very Far range.'),
('stride-potion','Stride Potion','Gain +1 bonus to your next Agility Roll.'),
('sun-tree-sap','Sun Tree Sap','Roll a d6 for varied healing or resurrection effects.'),
('sweet-moss','Sweet Moss','During rest, clear 1d10 HP or 1d10 Stress.'),
('unstable-arcane-shard','Unstable Arcane Shard','Throw to deal 1d20 magic damage to Far-range adversaries on success.'),
('varik-leaves','Varik Leaves','Eat to immediately gain 2 Hope.'),
('vial-of-darksmoke','Vial of Darksmoke','Roll d6s equal to Agility and add the highest to Evasion against an attack.'),
('vial-of-moondrip','Vial of Moondrip','See in total darkness until your next rest.'),
('wingsprout','Wingsprout','Grow magic wings and fly for minutes equal to your level.');
