create table public.items (
  id bigint generated always as identity primary key,

  slug text not null unique,
  name text not null,

  description text not null,

  created_at timestamptz not null default now()
);
insert into public.items (slug, name, description)
values
('airblade-charm','Airblade Charm','Attach to a Melee weapon. Three times per rest, activate to attack a target within Close range.'),
('alistairs-torch','Alistair’s Torch','A magic torch whose light illuminates a cave bright as day.'),
('arcane-cloak','Arcane Cloak','A Spellcast wearer can adjust this cloak’s color, texture, and size at will.'),
('arcane-prism','Arcane Prism','Place and activate to give allies within Close range +1 to Spellcast Rolls; immobile while active; refreshes after a long rest.'),
('attune-relic','Attune Relic','Gain +1 Instinct. You can only carry one relic.'),
('bag-of-ficklesand','Bag of Ficklesand','Adjust weight with Presence (10); on Finesse (10), make a target Vulnerable.'),
('belt-of-unity','Belt of Unity','Once per session, spend 5 Hope to lead a Tag Team Roll with three PCs.'),
('bloodstone','Bloodstone','Attach to a featureless weapon to grant Brutal: rolling max damage adds an extra damage die.'),
('bolster-relic','Bolster Relic','Gain +1 Strength. You can only carry one relic.'),
('box-of-many-goods','Box of Many Goods','Once per long rest, roll d12 to possibly gain random common consumables.'),
('calming-pendant','Calming Pendant','When you would mark your last Stress, roll d6; on 5+, don’t mark it.'),
('charging-quiver','Charging Quiver','On a successful arrow attack, add your tier to the damage roll.'),
('charm-relic','Charm Relic','Gain +1 Presence. You can only carry one relic.'),
('clay-companion','Clay Companion','Sculpt into an animal companion that retains memory across forms.'),
('companion-case','Companion Case','A small animal companion inside is immune to all damage and harmful effects.'),
('control-relic','Control Relic','Gain +1 Finesse. You can only carry one relic.'),
('corrector-sprite','Corrector Sprite','Once per short rest, gain advantage on an attack roll.'),
('dual-flask','Dual Flask','Holds two liquids; switch between them with a small lever.'),
('elusive-amulet','Elusive Amulet','Once per long rest, become Hidden until you move, even if enemies approach.'),
('empty-chest','Empty Chest','Appears empty until a trigger reveals its stored contents.'),
('enlighten-relic','Enlighten Relic','Gain +1 Knowledge. You can only carry one relic.'),
('fire-jar','Fire Jar','Pour contents to instantly create fire; refills on a long rest.'),
('flickerfly-pendant','Flickerfly Pendant','Melee physical weapons can strike targets within Very Close range.'),
('gecko-gloves','Gecko Gloves','Climb vertical surfaces and ceilings.'),
('gem-of-alacrity','Gem of Alacrity','Attach to a weapon to use Agility for attack rolls.'),
('gem-of-audacity','Gem of Audacity','Attach to a weapon to use Presence for attack rolls.'),
('gem-of-insight','Gem of Insight','Attach to a weapon to use Instinct for attack rolls.'),
('gem-of-might','Gem of Might','Attach to a weapon to use Strength for attack rolls.'),
('gem-of-precision','Gem of Precision','Attach to a weapon to use Finesse for attack rolls.'),
('gem-of-sagacity','Gem of Sagacity','Attach to a weapon to use Knowledge for attack rolls.'),
('glamour-stone','Glamour Stone','Memorize someone’s appearance; spend Hope to illusion yourself as them.'),
('glider','Glider','While falling, mark a Stress to glide safely to the ground.'),
('greatstone','Greatstone','Attach to a featureless weapon to grant Powerful: roll extra damage die, discard lowest.'),
('homing-compasses','Homing Compasses','Two compasses that always point toward each other.'),
('honing-relic','Honing Relic','Gain +1 bonus to an Experience of your choice. You can only carry one relic.'),
('hopekeeper-locket','Hopekeeper Locket','Store Hope during rest; when at 0 Hope, expend it to gain 1 Hope.'),
('infinite-bag','Infinite Bag','Stores items in a limitless pocket dimension.'),
('lasketider-boots','Lasketider Boots','Walk on water as if it were soft ground.'),
('lorekeeper','Lorekeeper','Store details of up to three hostile creatures; gain +1 to rolls against them.'),
('manacles','Manacles','Locking cuffs with a key.'),
('minor-health-potion-recipe','Minor Health Potion Recipe','Downtime: use blood to craft a Minor Health Potion.'),
('minor-stamina-potion-recipe','Minor Stamina Potion Recipe','Downtime: use a bone to craft a Minor Stamina Potion.'),
('mythic-dust-recipe','Mythic Dust Recipe','Downtime: use fine gold dust to craft Mythic Dust.'),
('paragons-chain','Paragon’s Chain','Once per long rest, spend Hope to roll a d20 as Hope Die for aligned actions.'),
('phoenix-feather','Phoenix Feather','While unconscious, gain +1 to the roll to avoid a scar.'),
('piercing-arrows','Piercing Arrows','Three times per rest, add Proficiency to damage on a successful hit.'),
('piper-whistle','Piper Whistle','Produces a piercing sound audible up to 1 mile away.'),
('portal-seed','Portal Seed','Plant to grow a portal after 24 hours; connects to other portal seeds.'),
('premium-bedroll','Premium Bedroll','During downtime, automatically clear a Stress.'),
('ring-of-resistance','Ring of Resistance','Once per long rest, halve damage after a successful attack against you.'),
('ring-of-silence','Ring of Silence','Spend Hope to silence your footsteps until next rest.'),
('ring-of-unbreakable-resolve','Ring of Unbreakable Resolve','Once per session, spend 4 Hope to cancel a spent Fear.'),
('shard-of-memory','Shard of Memory','Once per long rest, spend 2 Hope to recall a domain card without its cost.'),
('skeleton-key','Skeleton Key','Gain advantage on the Finesse Roll to open a locked door.'),
('speaking-orbs','Speaking Orbs','A paired set that allows communication across any distance.'),
('stride-relic','Stride Relic','Gain +1 Agility. You can only carry one relic.'),
('suspended-rod','Suspended Rod','Activate to freeze the rod in place, ignoring gravity.'),
('valorstone','Valorstone','Attach to featureless armor to grant Resilient on last Armor Slot.'),
('vial-of-darksmoke-recipe','Vial of Darksmoke Recipe','Downtime: mark Stress to craft a Vial of Darksmoke.'),
('woven-net','Woven Net','Finesse Roll to trap a small creature; escape with Attack Roll (16).');
