create table public.weapons (
  id bigint generated always as identity primary key,

  slug text not null unique,
  name text not null,

  tier int not null,
  weapon_type text not null,   -- Primary / Secondary

  trait text not null,         -- Strength, Agility, Finesse, etc.
  range text not null,         -- Melee, Close, Far, Very Far
  damage text not null,        -- stored verbatim, e.g. "d6+11 phy"
  burden text not null,        -- One-Handed, Two-Handed

  feature_name text,
  feature_description text,

  created_at timestamptz not null default now()
);

insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'aantari-bow',
    'Aantari Bow',
    4,
    'Primary',
    'Finesse',
    'Far',
    'd6+11 phy',
    'Two-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'advanced-arcane-gauntlets',
    'Advanced Arcane Gauntlets',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd10+9 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-battleaxe',
    'Advanced Battleaxe',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd10+9 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-broadsword',
    'Advanced Broadsword',
    3,
    'Primary',
    'Agility',
    'Melee',
    'd8+6 phy',
    'One-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'advanced-crossbow',
    'Advanced Crossbow',
    3,
    'Primary',
    'Finesse',
    'Far',
    'd6+7 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-cutlass',
    'Advanced Cutlass',
    3,
    'Primary',
    'Presence',
    'Melee',
    'd8+7 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-dagger',
    'Advanced Dagger',
    3,
    'Primary',
    'Finesse',
    'Melee',
    'd8+7 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-dualstaff',
    'Advanced Dualstaff',
    3,
    'Primary',
    'Instinct',
    'Far',
    'd6+9 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-glowing-rings',
    'Advanced Glowing Rings',
    3,
    'Primary',
    'Agility',
    'Very Close',
    'd10+8 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-grappler',
    'Advanced Grappler',
    3,
    'Secondary',
    'Finesse',
    'Close',
    'd6+4 phy',
    'One-Handed',
    'Hooked',
    'On a successful attack, you can pull the target into Melee range.'
  ),
  (
    'advanced-greatstaff',
    'Advanced Greatstaff',
    3,
    'Primary',
    'Knowledge',
    'Very Far',
    'd6+6 mag',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'advanced-greatsword',
    'Advanced Greatsword',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd10+9 phy',
    'Two-Handed',
    'Massive',
    '-1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'advanced-halberd',
    'Advanced Halberd',
    3,
    'Primary',
    'Strength',
    'Very Close',
    'd10+8 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'advanced-hallowed-axe',
    'Advanced Hallowed Axe',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd8+7 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-hand-crossbow',
    'Advanced Hand Crossbow',
    3,
    'Secondary',
    'Finesse',
    'Far',
    'd6+5 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-hand-runes',
    'Advanced Hand Runes',
    3,
    'Primary',
    'Instinct',
    'Very Close',
    'd10+6 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-longbow',
    'Advanced Longbow',
    3,
    'Primary',
    'Agility',
    'Very Far',
    'd8+9 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'advanced-longsword',
    'Advanced Longsword',
    3,
    'Primary',
    'Agility',
    'Melee',
    'd10+9 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-mace',
    'Advanced Mace',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd8+7 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-quarterstaff',
    'Advanced Quarterstaff',
    3,
    'Primary',
    'Instinct',
    'Melee',
    'd10+9 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-rapier',
    'Advanced Rapier',
    3,
    'Primary',
    'Presence',
    'Melee',
    'd8+6 phy',
    'One-Handed',
    'Quick',
    'When you make an attack, you can mark a Stress to target another creature within range.'
  ),
  (
    'advanced-returning-blade',
    'Advanced Returning Blade',
    3,
    'Primary',
    'Finesse',
    'Close',
    'd8+6 mag',
    'One-Handed',
    'Returning',
    'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'
  ),
  (
    'advanced-round-shield',
    'Advanced Round Shield',
    3,
    'Secondary',
    'Strength',
    'Melee',
    'd4+4 phy',
    'One-Handed',
    'Protective',
    '+3 to Armor Score'
  ),
  (
    'advanced-scepter',
    'Advanced Scepter',
    3,
    'Primary',
    'Presence',
    'Far',
    'd6+6 mag',
    'Two-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Presence, Melee, d8+4.'
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'curved-dagger',
    'Curved Dagger',
    4,
    'Primary',
    'Finesse',
    'Melee',
    'd8+9 phy',
    'One-Handed',
    'Serrated',
    'When you roll a 1 on a damage die, it deals 8 damage instead.'
  ),
  (
    'cutlass',
    'Cutlass',
    1,
    'Primary',
    'Presence',
    'Melee',
    'd8+1 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'dagger',
    'Dagger',
    1,
    'Primary',
    'Finesse',
    'Melee',
    'd8+1 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'devouring-dagger',
    'Devouring Dagger',
    2,
    'Primary',
    'Finesse',
    'Melee',
    'd8+4 mag',
    'One-Handed',
    'Scary',
    'On a successful attack, the target must mark a Stress.'
  ),
  (
    'double-flail',
    'Double Flail',
    3,
    'Primary',
    'Agility',
    'Very Close',
    'd10+8 phy',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'dual-ended-sword',
    'Dual-Ended Sword',
    4,
    'Primary',
    'Agility',
    'Melee',
    'd10+9 phy',
    'Two-Handed',
    'Quick',
    'When you make an attack, you can mark a Stress to target another creature within range.'
  ),
  (
    'dualstaff',
    'Dualstaff',
    1,
    'Primary',
    'Instinct',
    'Far',
    'd6+3 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'ego-blade',
    'Ego Blade',
    2,
    'Primary',
    'Agility',
    'Melee',
    'd12+4 mag',
    'One-Handed',
    'Pompous',
    'You must have a Presence of 0 or lower to use this weapon.'
  ),
  (
    'elder-bow',
    'Elder Bow',
    2,
    'Primary',
    'Instinct',
    'Far',
    'd6+4 mag',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'extended-polearm',
    'Extended Polearm',
    4,
    'Primary',
    'Finesse',
    'Very Close',
    'd8+10 phy',
    'Two-Handed',
    'Long',
    'This weapon’s attack targets all adversaries in a line within range.'
  ),
  (
    'finehair-bow',
    'Finehair Bow',
    2,
    'Primary',
    'Agility',
    'Very Far',
    'd6+5 phy',
    'Two-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'firestaff',
    'Firestaff',
    3,
    'Primary',
    'Instinct',
    'Far',
    'd6+7 mag',
    'Two-Handed',
    'Burning',
    'When you roll a 6 on a damage die, the target must mark a Stress.'
  ),
  (
    'flickerfly-blade',
    'Flickerfly Blade',
    3,
    'Primary',
    'Agility',
    'Melee',
    'd8+5 phy',
    'One-Handed',
    'Sharpening',
    'Gain a bonus to your damage rolls equal to your Agility.'
  ),
  (
    'floating-bladeshards',
    'Floating Bladeshards',
    4,
    'Primary',
    'Instinct',
    'Close',
    'd8+9 mag',
    'One-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'fusion-gloves',
    'Fusion Gloves',
    4,
    'Primary',
    'Knowledge',
    'Very Far',
    'd6+9 mag',
    'Two-Handed',
    'Bonded',
    'Gain a bonus to your damage rolls equal to your level.'
  ),
  (
    'ghostblade',
    'Ghostblade',
    3,
    'Primary',
    'Presence',
    'Melee',
    'd10+7 phy or mag',
    'One-Handed',
    'Otherworldly',
    'On a successful attack, you can deal physical or magic damage.'
  ),
  (
    'gilded-bow',
    'Gilded Bow',
    3,
    'Primary',
    'Finesse',
    'Far',
    'd6+7 mag',
    'Two-Handed',
    'Self-Correcting',
    'When you roll a 1 on a damage die, it deals 6 damage instead.'
  ),
  (
    'gilded-falchion',
    'Gilded Falchion',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd10+4 phy',
    'One-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'glowing-rings',
    'Glowing Rings',
    1,
    'Primary',
    'Agility',
    'Very Close',
    'd10+2 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'grappler',
    'Grappler',
    1,
    'Secondary',
    'Finesse',
    'Close',
    'd6 phy',
    'One-Handed',
    'Hooked',
    'On a successful attack, you can pull the target into Melee range.'
  ),
  (
    'greatbow',
    'Greatbow',
    2,
    'Primary',
    'Strength',
    'Far',
    'd6+6 phy',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'greatstaff',
    'Greatstaff',
    1,
    'Primary',
    'Knowledge',
    'Very Far',
    'd6 mag',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'greatsword',
    'Greatsword',
    1,
    'Primary',
    'Strength',
    'Melee',
    'd10+3 phy',
    'Two-Handed',
    'Massive',
    '-1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'halberd',
    'Halberd',
    1,
    'Primary',
    'Strength',
    'Very Close',
    'd10+2 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'hallowed-axe',
    'Hallowed Axe',
    1,
    'Primary',
    'Strength',
    'Melee',
    'd8+1 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'hammer-of-exota',
    'Hammer of Exota',
    2,
    'Primary',
    'Instinct',
    'Melee',
    'd8+6 mag',
    'Two-Handed',
    'Eruptive',
    'On a successful attack against a target within Melee range, all other adversaries within Very Close range must succeed on a reaction roll (14) or take half damage.'
  ),
  (
    'hammer-of-wrath',
    'Hammer of Wrath',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd10+7 phy',
    'Two-Handed',
    'Devastating',
    'Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.'
  ),
  (
    'hand-cannon',
    'Hand Cannon',
    4,
    'Primary',
    'Finesse',
    'Very Far',
    'd6+12 phy',
    'One-Handed',
    'Reloading',
    'After you make an attack, roll a d6. On a 1, you must mark a Stress to reload this weapon before you can fire it again.'
  ),
  (
    'hand-crossbow',
    'Hand Crossbow',
    1,
    'Secondary',
    'Finesse',
    'Far',
    'd6+1 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'hand-runes',
    'Hand Runes',
    1,
    'Primary',
    'Instinct',
    'Very Close',
    'd10 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'hand-sling',
    'Hand Sling',
    3,
    'Secondary',
    'Finesse',
    'Very Close',
    'd6+4 phy',
    'One-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Finesse, Close, d8+4.'
  ),
  (
    'ilmari-s-rifle',
    'Ilmari''s Rifle',
    3,
    'Primary',
    'Finesse',
    'Very Far',
    'd6+6 mag',
    'One-Handed',
    'Reloading',
    'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'
  ),
  (
    'impact-gauntlet',
    'Impact Gauntlet',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd10+11 phy',
    'One-Handed',
    'Concussive',
    'On a successful attack, you can spend a Hope to knock the target back to Far range.'
  ),
  (
    'improved-arcane-gauntlets',
    'Improved Arcane Gauntlets',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd10+6 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-battleaxe',
    'Improved Battleaxe',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd10+6 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-broadsword',
    'Improved Broadsword',
    2,
    'Primary',
    'Agility',
    'Melee',
    'd8+3 phy',
    'One-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'improved-crossbow',
    'Improved Crossbow',
    2,
    'Primary',
    'Finesse',
    'Far',
    'd6+4 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-cutlass',
    'Improved Cutlass',
    2,
    'Primary',
    'Presence',
    'Melee',
    'd8+4 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-dagger',
    'Improved Dagger',
    2,
    'Primary',
    'Finesse',
    'Melee',
    'd8+4 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-dualstaff',
    'Improved Dualstaff',
    2,
    'Primary',
    'Instinct',
    'Far',
    'd6+6 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-glowing-rings',
    'Improved Glowing Rings',
    2,
    'Primary',
    'Agility',
    'Very Close',
    'd10+5 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-grappler',
    'Improved Grappler',
    2,
    'Secondary',
    'Finesse',
    'Close',
    'd6+2 phy',
    'One-Handed',
    'Hooked',
    'On a successful attack, you can pull the target into Melee range.'
  ),
  (
    'improved-greatstaff',
    'Improved Greatstaff',
    2,
    'Primary',
    'Knowledge',
    'Very Far',
    'd6+3 mag',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'improved-greatsword',
    'Improved Greatsword',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd10+6 phy',
    'Two-Handed',
    'Massive',
    '-1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'improved-halberd',
    'Improved Halberd',
    2,
    'Primary',
    'Strength',
    'Very Close',
    'd10+5 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'improved-hallowed-axe',
    'Improved Hallowed Axe',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd8+4 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-hand-crossbow',
    'Improved Hand Crossbow',
    2,
    'Secondary',
    'Finesse',
    'Far',
    'd6+3 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-hand-runes',
    'Improved Hand Runes',
    2,
    'Primary',
    'Instinct',
    'Very Close',
    'd10+3 mag',
    'One-Handed',
    null,
    null
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'improved-longbow',
    'Improved Longbow',
    2,
    'Primary',
    'Agility',
    'Very Far',
    'd8+6 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'improved-longsword',
    'Improved Longsword',
    2,
    'Primary',
    'Agility',
    'Melee',
    'd10+6 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-mace',
    'Improved Mace',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd8+4 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-quarterstaff',
    'Improved Quarterstaff',
    2,
    'Primary',
    'Instinct',
    'Melee',
    'd10+6 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-rapier',
    'Improved Rapier',
    2,
    'Primary',
    'Presence',
    'Melee',
    'd8+3 phy',
    'One-Handed',
    'Quick',
    'When you make an attack, you can mark a Stress to target another creature within range.'
  ),
  (
    'improved-returning-blade',
    'Improved Returning Blade',
    2,
    'Primary',
    'Finesse',
    'Close',
    'd8+3 mag',
    'One-Handed',
    'Returning',
    'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'
  ),
  (
    'improved-round-shield',
    'Improved Round Shield',
    2,
    'Secondary',
    'Strength',
    'Melee',
    'd4+2 phy',
    'One-Handed',
    'Protective',
    '+2 to Armor Score'
  ),
  (
    'improved-scepter',
    'Improved Scepter',
    2,
    'Primary',
    'Presence',
    'Far',
    'd6+3 mag',
    'Two-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Presence, Melee, d8+3.'
  ),
  (
    'improved-shortbow',
    'Improved Shortbow',
    2,
    'Primary',
    'Agility',
    'Far',
    'd6+6 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-shortstaff',
    'Improved Shortstaff',
    2,
    'Primary',
    'Instinct',
    'Close',
    'd8+4 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-shortsword',
    'Improved Shortsword',
    2,
    'Secondary',
    'Agility',
    'Melee',
    'd8+2 phy',
    'One-Handed',
    'Paired',
    '+3 to primary weapon damage to targets within Melee range'
  ),
  (
    'improved-small-dagger',
    'Improved Small Dagger',
    2,
    'Secondary',
    'Finesse',
    'Melee',
    'd8+2 phy',
    'One-Handed',
    'Paired',
    '+3 to primary weapon damage to targets within Melee range'
  ),
  (
    'improved-spear',
    'Improved Spear',
    2,
    'Primary',
    'Finesse',
    'Very Close',
    'd8+6 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'improved-tower-shield',
    'Improved Tower Shield',
    2,
    'Secondary',
    'Strength',
    'Melee',
    'd6+2 phy',
    'One-Handed',
    'Barrier',
    '+3 to Armor Score; -1 to Evasion'
  ),
  (
    'improved-wand',
    'Improved Wand',
    2,
    'Primary',
    'Knowledge',
    'Far',
    'd6+4 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'improved-warhammer',
    'Improved Warhammer',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd12+6 phy',
    'Two-Handed',
    'Heavy',
    '-1 to Evasion'
  ),
  (
    'improved-whip',
    'Improved Whip',
    2,
    'Secondary',
    'Presence',
    'Very Close',
    'd6+2 phy',
    'One-Handed',
    'Startling',
    'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'
  ),
  (
    'keepers-staff',
    'Keeper’s Staff',
    2,
    'Primary',
    'Knowledge',
    'Far',
    'd6+4 mag',
    'Two-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'knuckle-blades',
    'Knuckle Blades',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd10+6 phy',
    'One-Handed',
    'Brutal',
    'When you roll the maximum value on a damage die, roll an additional damage die.'
  ),
  (
    'knuckle-claws',
    'Knuckle Claws',
    4,
    'Secondary',
    'Strength',
    'Melee',
    'd6+8 phy',
    'One-Handed',
    'Doubled Up',
    'When you make an attack with your primary weapon, you can deal damage to another target within Melee range.'
  ),
  (
    'labrys-axe',
    'Labrys Axe',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd10+7 phy',
    'Two-Handed',
    'Protective',
    '+1 to Armor Score'
  ),
  (
    'legendary-arcane-gauntlets',
    'Legendary Arcane Gauntlets',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd10+12 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-battleaxe',
    'Legendary Battleaxe',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd10+12 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-broadsword',
    'Legendary Broadsword',
    4,
    'Primary',
    'Agility',
    'Melee',
    'd8+9 phy',
    'One-Handed',
    'Reliable',
    '+1 to attack rolls'
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'legendary-crossbow',
    'Legendary Crossbow',
    4,
    'Primary',
    'Finesse',
    'Far',
    'd6+10 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-cutlass',
    'Legendary Cutlass',
    4,
    'Primary',
    'Presence',
    'Melee',
    'd8+10 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-dagger',
    'Legendary Dagger',
    4,
    'Primary',
    'Finesse',
    'Melee',
    'd8+10 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-dualstaff',
    'Legendary Dualstaff',
    4,
    'Primary',
    'Instinct',
    'Far',
    'd8+12 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-glowing-rings',
    'Legendary Glowing Rings',
    4,
    'Primary',
    'Agility',
    'Very Close',
    'd10+11 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-grappler',
    'Legendary Grappler',
    4,
    'Secondary',
    'Finesse',
    'Close',
    'd6+6 phy',
    'One-Handed',
    'Hooked',
    'On a successful attack, you can pull the target into Melee range.'
  ),
  (
    'legendary-greatstaff',
    'Legendary Greatstaff',
    4,
    'Primary',
    'Knowledge',
    'Very Far',
    'd6+9 mag',
    'Two-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'legendary-greatsword',
    'Legendary Greatsword',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd10+12 phy',
    'Two-Handed',
    'Massive',
    '-1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'legendary-halberd',
    'Legendary Halberd',
    4,
    'Primary',
    'Strength',
    'Very Close',
    'd10+11 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'legendary-hallowed-axe',
    'Legendary Hallowed Axe',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd8+10 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-hand-crossbow',
    'Legendary Hand Crossbow',
    4,
    'Secondary',
    'Finesse',
    'Far',
    'd6+7 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-hand-runes',
    'Legendary Hand Runes',
    4,
    'Primary',
    'Instinct',
    'Very Close',
    'd10+9 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-longbow',
    'Legendary Longbow',
    4,
    'Primary',
    'Agility',
    'Very Far',
    'd8+12 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'legendary-longsword',
    'Legendary Longsword',
    4,
    'Primary',
    'Agility',
    'Melee',
    'd10+12 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-mace',
    'Legendary Mace',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd8+10 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-quarterstaff',
    'Legendary Quarterstaff',
    4,
    'Primary',
    'Instinct',
    'Melee',
    'd10+12 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-rapier',
    'Legendary Rapier',
    4,
    'Primary',
    'Presence',
    'Melee',
    'd8+9 phy',
    'One-Handed',
    'Quick',
    'When you make an attack, you can mark a Stress to target another creature within range.'
  ),
  (
    'legendary-returning-blade',
    'Legendary Returning Blade',
    4,
    'Primary',
    'Finesse',
    'Close',
    'd8+9 mag',
    'One-Handed',
    'Returning',
    'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'
  ),
  (
    'legendary-round-shield',
    'Legendary Round Shield',
    4,
    'Secondary',
    'Strength',
    'Melee',
    'd4+6 phy',
    'One-Handed',
    'Protective',
    '+4 to Armor Score'
  ),
  (
    'legendary-scepter',
    'Legendary Scepter',
    4,
    'Primary',
    'Presence',
    'Far',
    'd6+9 mag',
    'Two-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Presence, Melee, d8+6.'
  ),
  (
    'legendary-shortbow',
    'Legendary Shortbow',
    4,
    'Primary',
    'Agility',
    'Far',
    'd6+12 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-shortstaff',
    'Legendary Shortstaff',
    4,
    'Primary',
    'Instinct',
    'Close',
    'd8+10 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-shortsword',
    'Legendary Shortsword',
    4,
    'Secondary',
    'Agility',
    'Melee',
    'd8+6 phy',
    'One-Handed',
    'Paired',
    '+5 to primary weapon damage to targets within Melee range'
  ),
  (
    'legendary-small-dagger',
    'Legendary Small Dagger',
    4,
    'Secondary',
    'Finesse',
    'Melee',
    'd8+6 phy',
    'One-Handed',
    'Paired',
    '+5 to primary weapon damage to targets within Melee range'
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'legendary-spear',
    'Legendary Spear',
    4,
    'Primary',
    'Finesse',
    'Very Close',
    'd8+12 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'legendary-tower-shield',
    'Legendary Tower Shield',
    4,
    'Secondary',
    'Strength',
    'Melee',
    'd6+6 phy',
    'One-Handed',
    'Barrier',
    '+5 to Armor Score; -1 to Evasion.'
  ),
  (
    'legendary-wand',
    'Legendary Wand',
    4,
    'Primary',
    'Knowledge',
    'Far',
    'd6+10 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'legendary-warhammer',
    'Legendary Warhammer',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd12+12 phy',
    'Two-Handed',
    'Heavy',
    '-1 to Evasion'
  ),
  (
    'legendary-whip',
    'Legendary Whip',
    4,
    'Secondary',
    'Presence',
    'Very Close',
    'd6+6 phy',
    'One-Handed',
    'Startling',
    'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'
  ),
  (
    'longbow',
    'Longbow',
    1,
    'Primary',
    'Agility',
    'Very Far',
    'd8+3 phy',
    'Two-Handed',
    'Cumbersome',
    '-1 to Finesse'
  ),
  (
    'longsword',
    'Longsword',
    1,
    'Primary',
    'Agility',
    'Melee',
    'd10+3 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'mace',
    'Mace',
    1,
    'Primary',
    'Strength',
    'Melee',
    'd8+1 phy',
    'One-Handed',
    null,
    null
  ),
  (
    'mage-orb',
    'Mage Orb',
    3,
    'Primary',
    'Knowledge',
    'Far',
    'd6+7 mag',
    'One-Handed',
    'Powerful',
    'On a successful attack, roll an additional damage die and discard the lowest result.'
  ),
  (
    'magus-revolver',
    'Magus Revolver',
    4,
    'Primary',
    'Finesse',
    'Very Far',
    'd6+13 mag',
    'One-Handed',
    'Reloading',
    'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'
  ),
  (
    'meridian-cutlass',
    'Meridian Cutlass',
    3,
    'Primary',
    'Presence',
    'Melee',
    'd10+5 phy',
    'One-Handed',
    'Dueling',
    'When there are no other creatures within Close range of the target, gain advantage on your attack roll against them.'
  ),
  (
    'midas-scythe',
    'Midas Scythe',
    4,
    'Primary',
    'Knowledge',
    'Melee',
    'd10+9 mag',
    'Two-Handed',
    'Greedy',
    'Spend a handful of gold to gain a +1 bonus to your Proficiency on a damage roll.'
  ),
  (
    'parrying-dagger',
    'Parrying Dagger',
    2,
    'Secondary',
    'Finesse',
    'Melee',
    'd6+2 phy',
    'One-Handed',
    'Parry',
    'When you are attacked, roll this weapon’s damage dice. If any of the attacker’s damage dice rolled the same value as your dice, the matching results are discarded from the attacker’s damage dice before the damage you take is totaled.'
  ),
  (
    'powered-gauntlet',
    'Powered Gauntlet',
    3,
    'Secondary',
    'Knowledge',
    'Close',
    'd6+4 phy',
    'One-Handed',
    'Charged',
    'Mark a Stress to gain a +1 bonus to your Proficiency on a primary weapon attack.'
  ),
  (
    'primer-shard',
    'Primer Shard',
    4,
    'Secondary',
    'Instinct',
    'Very Close',
    'd4 phy',
    'One-Handed',
    'Locked On',
    'On a successful attack, your next attack against the same target with your primary weapon automatically succeeds.'
  ),
  (
    'quarterstaff',
    'Quarterstaff',
    1,
    'Primary',
    'Instinct',
    'Melee',
    'd10+3 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'rapier',
    'Rapier',
    1,
    'Primary',
    'Presence',
    'Melee',
    'd8 phy',
    'One-Handed',
    'Quick',
    'When you make an attack, you can mark a Stress to target another creature within range.'
  ),
  (
    'retractable-saber',
    'Retractable Saber',
    3,
    'Primary',
    'Presence',
    'Melee',
    'd10+7 phy',
    'One-Handed',
    'Retractable',
    'The blade can be hidden in the hilt to avoid detection.'
  ),
  (
    'returning-axe',
    'Returning Axe',
    2,
    'Secondary',
    'Agility',
    'Close',
    'd6+4 phy',
    'One-Handed',
    'Returning',
    'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'
  ),
  (
    'returning-blade',
    'Returning Blade',
    1,
    'Primary',
    'Finesse',
    'Close',
    'd8 mag',
    'One-Handed',
    'Returning',
    'When this weapon is thrown within its range, it appears in your hand immediately after the attack.'
  ),
  (
    'ricochet-axes',
    'Ricochet Axes',
    4,
    'Primary',
    'Agility',
    'Far',
    'd6+11 phy',
    'Two-Handed',
    'Bouncing',
    'Mark 1 or more Stress to hit that many targets in range of the attack.'
  ),
  (
    'round-shield',
    'Round Shield',
    1,
    'Secondary',
    'Strength',
    'Melee',
    'd4 phy',
    'One-Handed',
    'Protective',
    '+1 to Armor Score'
  ),
  (
    'runes-of-ruination',
    'Runes of Ruination',
    3,
    'Primary',
    'Knowledge',
    'Very Close',
    'd20+4 mag',
    'One-Handed',
    'Painful',
    'Each time you make a successful attack, you must mark a Stress.'
  ),
  (
    'scepter-of-elias',
    'Scepter of Elias',
    2,
    'Primary',
    'Presence',
    'Far',
    'd6+3 mag',
    'One-Handed',
    'Invigorating',
    'On a successful attack, roll a d4. On a result of 4, clear a Stress.'
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'scepter',
    'Scepter',
    1,
    'Primary',
    'Presence',
    'Far',
    'd6 mag',
    'Two-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Presence, Melee, d8.'
  ),
  (
    'shortbow',
    'Shortbow',
    1,
    'Primary',
    'Agility',
    'Far',
    'd6+3 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'shortstaff',
    'Shortstaff',
    1,
    'Primary',
    'Instinct',
    'Close',
    'd8+1 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'shortsword',
    'Shortsword',
    1,
    'Secondary',
    'Agility',
    'Melee',
    'd8 phy',
    'One-Handed',
    'Paired',
    '+2 to primary weapon damage to targets within Melee range'
  ),
  (
    'siphoning-gauntlets',
    'Siphoning Gauntlets',
    4,
    'Primary',
    'Presence',
    'Melee',
    'd10+9 mag',
    'Two-Handed',
    'Lifestealing',
    'On a successful attack, roll a d6. On a result of 6, clear a Hit Point or clear a Stress.'
  ),
  (
    'sledge-axe',
    'Sledge Axe',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd12+13 phy',
    'Two-Handed',
    'Destructive',
    '-1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.'
  ),
  (
    'small-dagger',
    'Small Dagger',
    1,
    'Secondary',
    'Finesse',
    'Melee',
    'd8 phy',
    'One-Handed',
    'Paired',
    '+2 to primary weapon damage to targets within Melee range'
  ),
  (
    'spear',
    'Spear',
    1,
    'Primary',
    'Finesse',
    'Very Close',
    'd8+3 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'spiked-bow',
    'Spiked Bow',
    3,
    'Primary',
    'Agility',
    'Very Far',
    'd6+7 phy',
    'Two-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Agility, Melee, d10+5.'
  ),
  (
    'spiked-shield',
    'Spiked Shield',
    2,
    'Secondary',
    'Strength',
    'Melee',
    'd6+2 phy',
    'One-Handed',
    'Double Duty',
    '+1 to Armor Score; +1 to primary weapon damage within Melee range'
  ),
  (
    'steelforged-halberd',
    'Steelforged Halberd',
    2,
    'Primary',
    'Strength',
    'Very Close',
    'd8+4 phy',
    'Two-Handed',
    'Scary',
    'On a successful attack, the target must mark a Stress.'
  ),
  (
    'swinging-ropeblade',
    'Swinging Ropeblade',
    4,
    'Primary',
    'Presence',
    'Close',
    'd8+9 phy',
    'One-Handed',
    'Grappling',
    'On a successful attack, you can spend a Hope to Restrain the target or pull them into Melee range with you.'
  ),
  (
    'sword-of-light-and-flame',
    'Sword of Light and Flame',
    4,
    'Primary',
    'Strength',
    'Melee',
    'd10+11 mag',
    'Two-Handed',
    'Hot',
    'This weapon cuts through solid material.'
  ),
  (
    'talon-blades',
    'Talon Blades',
    3,
    'Primary',
    'Finesse',
    'Close',
    'd10+7 phy',
    'Two-Handed',
    'Brutal',
    'When you roll the maximum value on a damage die, roll an additional damage die.'
  ),
  (
    'thistlebow',
    'Thistlebow',
    4,
    'Primary',
    'Instinct',
    'Far',
    'd6+13 mag',
    'Two-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'tower-shield',
    'Tower Shield',
    1,
    'Secondary',
    'Strength',
    'Melee',
    'd6 phy',
    'One-Handed',
    'Barrier',
    '+2 to Armor Score; -1 to Evasion'
  ),
  (
    'urok-broadsword',
    'Urok Broadsword',
    2,
    'Primary',
    'Finesse',
    'Melee',
    'd8+3 phy',
    'One-Handed',
    'Deadly',
    'When you deal Severe damage, the target must mark an additional HP.'
  ),
  (
    'wand-of-enthrallment',
    'Wand of Enthrallment',
    2,
    'Primary',
    'Presence',
    'Far',
    'd6+4 mag',
    'One-Handed',
    'Persuasive',
    'Before you make a Presence Roll, you can mark a Stress to gain a +2 bonus to the result.'
  ),
  (
    'wand-of-essek',
    'Wand of Essek',
    4,
    'Primary',
    'Knowledge',
    'Far',
    'd8+13 mag',
    'One-Handed',
    'Timebending',
    'You can choose the target of your attack after making your attack roll.'
  ),
  (
    'wand',
    'Wand',
    1,
    'Primary',
    'Knowledge',
    'Far',
    'd6+1 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'war-scythe',
    'War Scythe',
    2,
    'Primary',
    'Finesse',
    'Very Close',
    'd8+5 phy',
    'Two-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'warhammer',
    'Warhammer',
    1,
    'Primary',
    'Strength',
    'Melee',
    'd12+3 phy',
    'Two-Handed',
    'Heavy',
    '-1 to Evasion'
  ),
  (
    'whip',
    'Whip',
    1,
    'Secondary',
    'Presence',
    'Very Close',
    'd6 phy',
    'One-Handed',
    'Startling',
    'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'
  ),
  (
    'widgast-pendant',
    'Widgast Pendant',
    3,
    'Primary',
    'Knowledge',
    'Close',
    'd10+5 mag',
    'One-Handed',
    'Timebending',
    'You choose the target of your attack after making your attack roll.'
  ),
  (
    'yutari-bloodbow',
    'Yutari Bloodbow',
    2,
    'Primary',
    'Finesse',
    'Far',
    'd6+4 mag',
    'Two-Handed',
    'Brutal',
    'When you roll the maximum value on a damage die, roll an additional damage die.'
  );
insert into public.weapons
  (slug, name, tier, weapon_type, trait, range, damage, burden, feature_name, feature_description)
values
  (
    'advanced-shortbow',
    'Advanced Shortbow',
    3,
    'Primary',
    'Agility',
    'Far',
    'd6+9 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-shortstaff',
    'Advanced Shortstaff',
    3,
    'Primary',
    'Instinct',
    'Close',
    'd8+7 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-shortsword',
    'Advanced Shortsword',
    3,
    'Secondary',
    'Agility',
    'Melee',
    'd8+4 phy',
    'One-Handed',
    'Paired',
    '+4 to primary weapon damage to targets within Melee range'
  ),
  (
    'advanced-small-dagger',
    'Advanced Small Dagger',
    3,
    'Secondary',
    'Finesse',
    'Melee',
    'd8+4 phy',
    'One-Handed',
    'Paired',
    '+4 to primary weapon damage to targets within Melee range'
  ),
  (
    'advanced-spear',
    'Advanced Spear',
    3,
    'Primary',
    'Finesse',
    'Very Close',
    'd8+9 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'advanced-tower-shield',
    'Advanced Tower Shield',
    3,
    'Secondary',
    'Strength',
    'Melee',
    'd6+4 phy',
    'One-Handed',
    'Barrier',
    '+4 to Armor Score; -1 to Evasion'
  ),
  (
    'advanced-wand',
    'Advanced Wand',
    3,
    'Primary',
    'Knowledge',
    'Far',
    'd6+7 mag',
    'One-Handed',
    null,
    null
  ),
  (
    'advanced-warhammer',
    'Advanced Warhammer',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd12+9 phy',
    'Two-Handed',
    'Heavy',
    '-1 to Evasion'
  ),
  (
    'advanced-whip',
    'Advanced Whip',
    3,
    'Secondary',
    'Presence',
    'Very Close',
    'd6+4 phy',
    'One-Handed',
    'Startling',
    'Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.'
  ),
  (
    'arcane-gauntlets',
    'Arcane Gauntlets',
    1,
    'Primary',
    'Strength',
    'Melee',
    'd10+3 mag',
    'Two-Handed',
    null,
    null
  ),
  (
    'axe-of-fortunis',
    'Axe of Fortunis',
    3,
    'Primary',
    'Strength',
    'Melee',
    'd10+8 mag',
    'Two-Handed',
    'Lucky',
    'On a failed attack, you can mark a Stress to reroll your attack.'
  ),
  (
    'battleaxe',
    'Battleaxe',
    1,
    'Primary',
    'Strength',
    'Melee',
    'd10+3 phy',
    'Two-Handed',
    null,
    null
  ),
  (
    'black-powder-revolver',
    'Black Powder Revolver',
    3,
    'Primary',
    'Finesse',
    'Far',
    'd6+8 phy',
    'One-Handed',
    'Reloading',
    'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'
  ),
  (
    'bladed-whip',
    'Bladed Whip',
    2,
    'Primary',
    'Agility',
    'Very Close',
    'd8+3 phy',
    'One-Handed',
    'Quick',
    'When you make an attack, you can mark a Stress to target another creature within range.'
  ),
  (
    'blessed-anlace',
    'Blessed Anlace',
    3,
    'Primary',
    'Instinct',
    'Melee',
    'd10+6 mag',
    'One-Handed',
    'Healing',
    'During downtime, automatically clear a Hit Point.'
  ),
  (
    'bloodstaff',
    'Bloodstaff',
    4,
    'Primary',
    'Instinct',
    'Far',
    'd20+7 mag',
    'Two-Handed',
    'Painful',
    'Each time you make a successful attack, you must mark a Stress.'
  ),
  (
    'blunderbuss',
    'Blunderbuss',
    2,
    'Primary',
    'Finesse',
    'Close',
    'd8+6 phy',
    'Two-Handed',
    'Reloading',
    'After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.'
  ),
  (
    'braveshield',
    'Braveshield',
    4,
    'Secondary',
    'Agility',
    'Melee',
    'd4+6 phy',
    'One-Handed',
    'Sheltering',
    'When you mark an Armor Slot, it reduces damage for you and all allies within Melee range of you who took the same damage.'
  ),
  (
    'broadsword',
    'Broadsword',
    1,
    'Primary',
    'Agility',
    'Melee',
    'd8 phy',
    'One-Handed',
    'Reliable',
    '+1 to attack rolls'
  ),
  (
    'buckler',
    'Buckler',
    3,
    'Secondary',
    'Agility',
    'Melee',
    'd4+4 phy',
    'One-Handed',
    'Deflecting',
    'When you are attacked, you can mark an Armor Slot to gain a bonus to your Evasion equal to your available Armor Slots against the attack.'
  ),
  (
    'casting-sword',
    'Casting Sword',
    2,
    'Primary',
    'Strength',
    'Melee',
    'd10+4 mag',
    'Two-Handed',
    'Versatile',
    'This weapon can also be used with these statistics—Knowledge, Far, d6+3.'
  ),
  (
    'crossbow',
    'Crossbow',
    1,
    'Primary',
    'Finesse',
    'Far',
    'd6+1 phy',
    'One-Handed',
    null,
    null
  );
